import { randomBytes, randomUUID } from "node:crypto";
import { spawn, spawnSync } from "node:child_process";
import { createWriteStream } from "node:fs";
import { chmod, mkdir, readFile, rename, rm, stat, writeFile } from "node:fs/promises";
import os from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { createClient } from "@supabase/supabase-js";
import { DashboardOverviewSchema, SessionLoginResponseSchema } from "@template/contracts";
import { isDebugCaptureActive, mergeBrowserPageVisited, mergeProductStatus } from "./agent-testing-helpers.mjs";
import { addRequiredEvidence, enforceEvidenceGate, hasBrowserDebugCapture, updateEvidenceState } from "./agent-testing-evidence.mjs";
import {
  cleanupOwnedResources,
  createStartupLifecycle,
  ownerMarkersMatch,
  runCancellableStartupChecks,
  startOwnedStack,
  startupCheckpoint,
  startupStage,
  supervisorCleanupMode,
  terminateVerifiedProcess,
  viteListenerOwnerMarkers,
  viteProcessOwnerMarkers
} from "./agent-testing-lifecycle.mjs";
import { initialAdmin, initialAdminPassword } from "./initial-admin-credentials.mjs";
import { createIsolatedProject, reservePorts } from "./check-migrations.mjs";

export const projectRoot = resolve(fileURLToPath(new URL("..", import.meta.url)));
const frontendRoot = join(projectRoot, "frontend");
const pnpm = process.platform === "win32" ? "pnpm.cmd" : "pnpm";
const stateRoot = join(os.tmpdir(), "fullstack-admin-agent-testing");
const reportsRoot = join(frontendRoot, "test-results", "agent-testing");

function redact(text) {
  return text
    .replace(/(service[_ -]?role[_ -]?key|secret[_ -]?key)(\s*[:=]\s*)[^\s"']+/gi, "$1$2[REDACTED]")
    .replace(/\bsb_secret_[a-zA-Z0-9_-]+/g, "[REDACTED]")
    .replace(/\beyJ[a-zA-Z0-9_.-]{24,}/g, "[REDACTED]")
    .replace(/(postgres(?:ql)?:\/\/[^:/\s]+:)[^@\s]+@/gi, "$1[REDACTED]@");
}

function runSync(command, args, options = {}) {
  const result = spawnSync(command, args, {
    cwd: options.cwd ?? projectRoot,
    encoding: "utf8",
    timeout: options.timeout ?? 180_000,
    stdio: ["ignore", "pipe", "pipe"],
    env: { ...process.env, SUPABASE_TELEMETRY_DISABLED: "1", ...options.env },
    shell: process.platform === "win32"
  });
  if (result.error || result.status !== 0) {
    const output = redact(`${result.stdout ?? ""}\n${result.stderr ?? ""}`).trim();
    throw new Error(`${command} failed (${result.error?.message ?? `exit code ${result.status ?? 1}`})${output ? `\n${output.slice(-2600)}` : ""}`);
  }
  return result.stdout ?? "";
}

function projectCli(root, args, options = {}) {
  return runSync(pnpm, ["--filter", "fullstack-admin-frontend", "exec", "supabase", "--workdir", root, ...args], options);
}

function identityFor(pid) {
  if (process.platform !== "darwin" && process.platform !== "linux") {
    throw new Error("Agent process recovery currently requires macOS or Linux process start identities");
  }
  const result = spawnSync("ps", ["-ww", "-p", String(pid), "-o", "stat=", "-o", "lstart=", "-o", "command="], {
    encoding: "utf8",
    stdio: ["ignore", "pipe", "ignore"]
  });
  if (result.status !== 0 || !result.stdout.trim()) return null;
  const match = result.stdout.trim().match(/^(\S+)\s+(.+)$/);
  if (!match || /^[zZ]/.test(match[1])) return null;
  return match[2].trim();
}

function safeRunId(value) {
  if (typeof value !== "string" || !/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value)) {
    throw new Error("run-id must be a UUID generated by this command");
  }
  return value;
}

async function atomicJson(path, value) {
  const temporary = `${path}.${randomUUID()}.tmp`;
  await writeFile(temporary, `${JSON.stringify(value, null, 2)}\n`, { mode: 0o600 });
  await rename(temporary, path);
  await chmod(path, 0o600);
}

async function readRun(runId) {
  const root = join(stateRoot, safeRunId(runId));
  const recordPath = join(root, "run.json");
  const record = JSON.parse(await readFile(recordPath, "utf8"));
  if (record.runId !== runId || record.stateRoot !== root) throw new Error("Run record ownership did not match");
  return { root, recordPath, record };
}

function parseArgs(args) {
  if (args[0] === "--") args = args.slice(1);
  const parsed = {};
  for (let index = 0; index < args.length; index += 1) {
    const key = args[index];
    if (!key.startsWith("--")) throw new Error(`Unexpected argument: ${key}`);
    if (Object.hasOwn(parsed, key)) throw new Error(`Duplicate option: ${key}`);
    const value = args[++index];
    if (!value || value.startsWith("--")) throw new Error(`Expected a value after ${key}`);
    parsed[key] = value;
  }
  return parsed;
}

function parseJson(output, description) {
  try {
    return JSON.parse(output);
  } catch {
    throw new Error(`${description} did not return valid JSON`);
  }
}

function stopBrowserSession(sessionId) {
  runSync("bsk", ["session", "stop", sessionId], { timeout: 20_000 });
}

function browserSessionPresent(record, run = runSync) {
  const sessions = parseJson(run("bsk", ["session", "list", "--json"], {
    timeout: 10_000,
    env: { BSK_AUTO_START: "0" }
  }), "BrowserSkill session list");
  const session = sessions.find(item => item.session_id === record.browser?.sessionId);
  if (!session) return false;
  if (session.browser_instance_id !== record.browser?.instanceId) {
    const error = new Error("BrowserSkill session is attached to a different instance than this run");
    error.code = "BSK_INSTANCE_MISMATCH";
    throw error;
  }
  return true;
}

function preflightBrowser(browserId) {
  const status = parseJson(runSync("bsk", ["status", "--json"], {
    timeout: 10_000,
    env: { BSK_AUTO_START: "0" }
  }), "BrowserSkill status");
  const browser = status.browsers?.find(instance => instance.instance_id === browserId);
  if (!browser || browser.unresponsive) throw new Error(`BrowserSkill instance ${browserId} is not connected and responsive`);

  const listed = parseJson(runSync("bsk", ["browsers", "--json"], {
    timeout: 10_000,
    env: { BSK_AUTO_START: "0" }
  }), "BrowserSkill browser list");
  if (!listed.some(instance => instance.instance_id === browserId && !instance.unresponsive)) {
    throw new Error(`BrowserSkill instance ${browserId} is not available`);
  }

  const session = parseJson(runSync("bsk", ["session", "start", "--browser", browserId, "--json"], {
    timeout: 20_000,
    env: { BSK_AUTO_START: "0" }
  }), "BrowserSkill session start");
  if (session.browser_instance_id !== browserId || typeof session.session_id !== "string") {
    if (typeof session.session_id === "string") stopBrowserSession(session.session_id);
    throw new Error("BrowserSkill started a session on an unexpected browser instance");
  }

  try {
    const capabilities = parseJson(runSync("bsk", ["debug", "capabilities", "--session", session.session_id], {
      timeout: 20_000,
      env: { BSK_AUTO_START: "0" }
    }), "BrowserSkill debug capability check");
    const actions = capabilities.capabilities?.actions ?? [];
    for (const required of ["start", "stop", "status", "export"]) {
      if (!actions.includes(required)) throw new Error(`BrowserSkill debug capability ${required} is unavailable`);
    }
    return {
      browserId,
      sessionId: session.session_id,
      daemonVersion: status.daemon_version ?? null,
      browserVersion: browser.browser_version ?? null,
      extensionVersion: browser.extension_version ?? null
    };
  } catch (error) {
    try { stopBrowserSession(session.session_id); } catch { /* preserve the original preflight failure */ }
    throw error;
  }
}

function preflightDocker() {
  runSync("docker", ["info", "--format", "{{.ServerVersion}}"], { timeout: 12_000 });
}

function spawnManaged(command, args, { cwd, env, logPath, runId }) {
  const log = createWriteStream(logPath, { flags: "a", mode: 0o600 });
  const child = spawn(command, args, {
    cwd,
    env: { ...process.env, SUPABASE_TELEMETRY_DISABLED: "1", AGENT_TEST_RUN_ID: runId, ...env },
    stdio: ["ignore", "pipe", "pipe"],
    detached: process.platform !== "win32",
    shell: process.platform === "win32",
    windowsHide: true
  });
  child.stdout?.on("data", chunk => log.write(redact(String(chunk))));
  child.stderr?.on("data", chunk => log.write(redact(String(chunk))));
  child.once("close", () => log.end());
  return child;
}

function processIsRunning(child) {
  return child.exitCode === null && child.signalCode === null;
}

async function waitForExit(child, timeoutMs) {
  if (child.closed) return true;
  return await new Promise(resolve => {
    const timer = setTimeout(() => finish(false), timeoutMs);
    const finish = result => {
      clearTimeout(timer);
      child.off("close", onClose);
      resolve(result);
    };
    const onClose = () => finish(true);
    child.once("close", onClose);
    if (child.closed) finish(true);
  });
}

function signalManagedProcess(pid, signal) {
  if (process.platform !== "win32") {
    try {
      return process.kill(-pid, signal);
    } catch (groupError) {
      if (groupError?.code !== "ESRCH") throw groupError;
      try {
        return process.kill(pid, signal);
      } catch (processError) {
        if (processError?.code === "ESRCH") return false;
        throw processError;
      }
    }
  }
  return process.kill(pid, signal);
}

async function stopChild(child, label, failures) {
  if (!child || child.closed) return;
  try {
    signalManagedProcess(child.pid, "SIGTERM");
    if (await waitForExit(child, 5_000)) return;
    signalManagedProcess(child.pid, "SIGKILL");
    if (await waitForExit(child, 2_000)) return;
    failures.push(`${label} subprocess did not exit after SIGKILL`);
  } catch (error) {
    failures.push(`${label} subprocess could not be stopped: ${error instanceof Error ? error.message : String(error)}`);
  }
}

function listeningPids(port) {
  if (!Number.isInteger(port) || port < 1 || port > 65535) return [];
  const result = spawnSync("lsof", ["-nP", `-iTCP:${port}`, "-sTCP:LISTEN", "-t"], {
    encoding: "utf8",
    stdio: ["ignore", "pipe", "ignore"]
  });
  if (result.status !== 0) return [];
  return [...new Set((result.stdout ?? "").split(/\s+/).map(Number).filter(pid => Number.isInteger(pid) && pid > 0))];
}

async function stopVerifiedPid(pid, label, expectedIdentity, ownerMarker, failures) {
  try {
    await terminateVerifiedProcess({
      pid,
      label,
      expectedIdentity,
      ownerMarkers: Array.isArray(ownerMarker) ? ownerMarker : [ownerMarker]
    }, {
      identityFor,
      signal: signalManagedProcess,
      waitForExit: (targetPid, identity, timeoutMs) => waitForIdentityChange(targetPid, identity, timeoutMs)
    });
  } catch (error) {
    failures.push(`${label} PID could not be stopped: ${error instanceof Error ? error.message : String(error)}`);
  }
}

async function waitForIdentityChange(pid, expectedIdentity, timeoutMs) {
  const deadline = Date.now() + timeoutMs;
  while (Date.now() < deadline) {
    if (identityFor(pid) !== expectedIdentity) return true;
    await new Promise(resolveDelay => setTimeout(resolveDelay, 100));
  }
  return identityFor(pid) !== expectedIdentity;
}

async function stopViteListener(record, failures) {
  const port = record.ports?.vite;
  const saved = record.children?.viteListener;
  const listenerMarkers = viteListenerOwnerMarkers(port, frontendRoot);
  const pids = new Set([...(saved?.pid ? [saved.pid] : []), ...listeningPids(port)]);
  for (const pid of pids) {
    const expected = pid === saved?.pid ? saved.identity : undefined;
    const current = identityFor(pid);
    const isOwnedVite = ownerMarkersMatch(current, listenerMarkers);
    if (expected || isOwnedVite) {
      await stopVerifiedPid(pid, "Vite listener", expected, listenerMarkers, failures);
    }
  }
  const remainingOwnedListeners = listeningPids(port)
    .map(pid => ({ pid, identity: identityFor(pid) }))
    .filter(listener => ownerMarkersMatch(listener.identity, listenerMarkers));
  for (const listener of remainingOwnedListeners) {
    failures.push(`Vite listener PID ${listener.pid} is still running after cleanup`);
  }
}

async function poll(child, label, check, timeoutMs = 30_000, lifecycle, abortSignal) {
  const deadline = Date.now() + timeoutMs;
  let last = "not ready";
  while (Date.now() < deadline) {
    lifecycle?.throwIfCancelled();
    if (abortSignal?.aborted) throw new Error(`${label} readiness check cancelled after a sibling failed`);
    if (child && !processIsRunning(child)) throw new Error(`${label} exited before becoming ready`);
    try {
      if (await check()) return;
    } catch (error) {
      last = error instanceof Error ? error.message : String(error);
    }
    await new Promise(resolveDelay => setTimeout(resolveDelay, 400));
  }
  throw new Error(`${label} did not become ready: ${last}`);
}

async function waitForApp(child, origin, lifecycle, abortSignal) {
  await poll(child, "Vite", async () => {
    const response = await fetch(`${origin}/`, { signal: AbortSignal.timeout(2_000) });
    return response.ok;
  }, 30_000, lifecycle, abortSignal);
}

async function waitForEdge(child, apiUrl, publishableKey, origin, lifecycle, abortSignal) {
  let postAllowOrigin;
  await poll(child, "Edge Functions", async () => {
    const response = await fetch(`${apiUrl}/functions/v1/session-login`, {
      method: "POST",
      headers: { apikey: publishableKey, "content-type": "application/json", Origin: origin },
      body: JSON.stringify({ loginName: "__agent_readiness_probe__", password: "invalid-readiness-password" }),
      signal: AbortSignal.timeout(2_000)
    });
    const data = await response.json().catch(() => null);
    if (response.status !== 401 || data?.error?.code !== "INVALID_CREDENTIALS") return false;
    postAllowOrigin = response.headers.get("access-control-allow-origin");
    return true;
  }, 30_000, lifecycle, abortSignal);
  if (abortSignal?.aborted) throw new Error("Edge readiness check cancelled after a sibling failed");
  if (postAllowOrigin !== origin && postAllowOrigin !== "*") {
    throw new Error(`session-login CORS rejected the allowed origin (Access-Control-Allow-Origin: ${postAllowOrigin ?? "<missing>"})`);
  }

  const response = await fetch(`${apiUrl}/functions/v1/session-login`, {
    method: "OPTIONS",
    headers: {
      Origin: origin,
      "access-control-request-method": "POST",
      "access-control-request-headers": "apikey,authorization,content-type"
    },
    signal: AbortSignal.timeout(3_000)
  });
  const allowedOrigin = response.headers.get("access-control-allow-origin");
  if (!response.ok || (allowedOrigin !== origin && allowedOrigin !== "*")) {
    throw new Error(`Edge Function OPTIONS CORS denied the selected Vite origin (status ${response.status}, Access-Control-Allow-Origin: ${allowedOrigin ?? "<missing>"})`);
  }
  const allowedHeaders = response.headers.get("access-control-allow-headers")?.toLowerCase() ?? "";
  for (const header of ["apikey", "authorization", "content-type"]) {
    if (!allowedHeaders.includes(header)) throw new Error(`Edge Function CORS did not allow ${header}`);
  }
}

function assertLocalStatus(values) {
  const apiUrl = values.API_URL ?? values.api_url;
  const publishableKey = values.PUBLISHABLE_KEY ?? values.ANON_KEY;
  const serviceRoleKey = values.SERVICE_ROLE_KEY ?? values.service_role_key ?? values.SECRET_KEY;
  if (!/^http:\/\/(127\.0\.0\.1|localhost):\d+$/.test(apiUrl ?? "")) {
    throw new Error("Temporary Supabase API did not return an explicit loopback URL");
  }
  if (typeof publishableKey !== "string" || !publishableKey || typeof serviceRoleKey !== "string" || !serviceRoleKey) {
    throw new Error("Temporary Supabase did not return its local keys");
  }
  return { apiUrl, publishableKey, serviceRoleKey };
}

async function provisionAgentFixture(admin, runId, credentials) {
  const { data: profile, error: profileError } = await admin.from("profiles")
    .select("id,auth_user_id,login_name,email")
    .eq("login_name", initialAdmin.loginName)
    .single();
  if (profileError || !profile || !profile.auth_user_id) throw new Error("setup:admin did not create a verified local administrator profile");
  credentials.profileId = String(profile.id);
  credentials.authUserId = profile.auth_user_id;

  const messageMarker = `__AGENT_${runId}`;
  const { data: message, error: messageError } = await admin.from("messages").insert({
    receiver_id: profile.id,
    title: `${messageMarker}_TODO`,
    summary: "Disposable unread Dashboard pilot task",
    content: `Disposable agent test fixture ${runId}`,
    message_type: "NOTICE",
    read_status: false,
    created_by: profile.id
  }).select("id").single();
  if (messageError || !message) throw new Error("Could not create the temporary unread message");
  credentials.messageId = String(message.id);

  const operationMarker = `${messageMarker}_OPERATION`;
  const { data: operation, error: operationError } = await admin.from("operation_logs").insert({
    operator_id: profile.id,
    operator_name: operationMarker,
    module_code: "DASHBOARD_PILOT",
    operation_type: "VERIFY",
    request_method: "GET",
    request_path: `/agent-testing/${runId}`,
    request_params: { runId },
    operation_result: 1
  }).select("id").single();
  if (operationError || !operation) throw new Error("Could not create the temporary Dashboard activity record");
  credentials.operationId = String(operation.id);
  credentials.operationMarker = operationMarker;
  return {
    loginName: profile.login_name,
    password: initialAdminPassword,
    email: profile.email,
    authUserId: profile.auth_user_id,
    profileId: credentials.profileId
  };
}

async function callerRequest(apiUrl, publishableKey, origin, accessToken, path, body) {
  const response = await fetch(`${apiUrl}${path}`, {
    method: "POST",
    headers: {
      apikey: publishableKey,
      Authorization: `Bearer ${accessToken}`,
      "content-type": "application/json",
      Origin: origin
    },
    body: JSON.stringify(body),
    signal: AbortSignal.timeout(8_000)
  });
  if (!response.ok) throw new Error(`Authenticated caller request ${path} failed with status ${response.status}`);
  return await response.json();
}

async function verifyCallerAccess({ apiUrl, publishableKey, origin, credentials, password }) {
  const loginResponse = await fetch(`${apiUrl}/functions/v1/session-login`, {
    method: "POST",
    headers: { apikey: publishableKey, "content-type": "application/json", Origin: origin },
    body: JSON.stringify({ loginName: credentials.loginName, password }),
    signal: AbortSignal.timeout(10_000)
  });
  const loginBody = SessionLoginResponseSchema.parse(await loginResponse.json().catch(() => null));
  if (!loginResponse.ok || loginBody.success !== true) {
    const code = loginBody.success ? "<unexpected-success>" : loginBody.error.code;
    const fieldState = {
      loginNameType: typeof credentials.loginName,
      loginNameLength: typeof credentials.loginName === "string" ? credentials.loginName.length : null,
      passwordType: typeof password,
      passwordLength: typeof password === "string" ? password.length : null
    };
    throw new Error(`The Dashboard account/password session could not be established (HTTP ${loginResponse.status}, code ${code}, fields ${JSON.stringify(fieldState)})`);
  }
  if (loginBody.data.session.profile.id !== credentials.profileId) throw new Error("session-login returned a different business profile");
  const accessToken = loginBody.data.tokens.accessToken;
  let checked;
  let verificationFailure;
  try {
    const navigation = await callerRequest(apiUrl, publishableKey, origin, accessToken, "/rest/v1/rpc/current_navigation", {});
    if (!Array.isArray(navigation) || !navigation.some(entry => entry.routeKey === "dashboard.overview" && entry.path === "/welcome")) {
      throw new Error("The registered caller Session cannot read the seeded Dashboard navigation");
    }
    if (!navigation.some(entry => entry.routeKey === "communication.messages" && entry.path === "/operation/messages")) {
      throw new Error("The registered caller Session cannot read the seeded message navigation");
    }

    const rawOverview = await callerRequest(apiUrl, publishableKey, origin, accessToken, "/rest/v1/rpc/dashboard_overview", {});
    const overview = DashboardOverviewSchema.parse(rawOverview);
    if (!overview.todoMessages.some(message => message.id === credentials.messageId && message.title === `__AGENT_${credentials.runId}_TODO`)) {
      throw new Error("The caller-scoped Dashboard RPC did not return its unread message fixture");
    }
    if (!overview.recentOperations.some(operation => operation.id === credentials.operationId && operation.operatorName === credentials.operationMarker)) {
      throw new Error("The caller-scoped Dashboard RPC did not return its operation fixture");
    }

    const messageUrl = new URL("/rest/v1/message_read_model", apiUrl);
    messageUrl.searchParams.set("select", "id,receiver_id,title");
    messageUrl.searchParams.set("id", `eq.${credentials.messageId}`);
    const messageResponse = await fetch(messageUrl, {
      headers: { apikey: publishableKey, Authorization: `Bearer ${accessToken}`, Origin: origin },
      signal: AbortSignal.timeout(8_000)
    });
    if (!messageResponse.ok) throw new Error(`Authenticated caller message read failed with status ${messageResponse.status}`);
    const rows = await messageResponse.json();
    if (!Array.isArray(rows) || rows.length !== 1 || String(rows[0].receiver_id) !== credentials.profileId) {
      throw new Error("The registered caller Session cannot read its own message fixture");
    }
    checked = { navigation, overview, message: rows[0] };
  } catch (error) {
    verificationFailure = new Error("The authenticated Dashboard caller checks failed", { cause: error });
  }

  const revoked = await fetch(`${apiUrl}/rest/v1/rpc/revoke_account_password_session`, {
    method: "POST",
    headers: {
      apikey: publishableKey,
      Authorization: `Bearer ${accessToken}`,
      "content-type": "application/json",
      Origin: origin
    },
    body: "{}",
    signal: AbortSignal.timeout(8_000)
  }).then(async response => response.ok && await response.json().catch(() => false) === true).catch(() => false);
  if (!revoked) {
    const revokeFailure = new Error("The readiness probe could not revoke its captured caller Session");
    if (verificationFailure) throw new AggregateError([verificationFailure, revokeFailure], "Caller verification and Session revocation both failed");
    throw revokeFailure;
  }
  if (verificationFailure) throw verificationFailure;
  return checked;
}

function reportPath(runId) {
  return join(reportsRoot, runId, "report.json");
}

async function publishReport(record) {
  const target = reportPath(record.runId);
  await mkdir(dirname(target), { recursive: true });
  await atomicJson(target, {
    schemaVersion: 1,
    runId: record.runId,
    scenario: record.scenario,
    commit: record.commit,
    browser: record.browser,
    appOrigin: record.appOrigin,
    startedAt: record.startedAt,
    finishedAt: new Date().toISOString(),
    productStatus: record.productStatus ?? "Unknown",
    productReason: record.productReason ?? null,
    cleanupStatus: record.cleanupFailures?.length ? "Failed" : "Succeeded",
    cleanupFailures: record.cleanupFailures ?? [],
    cleanupHistory: record.cleanupHistory ?? [],
    retainedProjectRoot: record.retainedProjectRoot ?? null,
    stackMayExist: record.stackMayExist === true || record.stackStarted === true,
    evidenceStatus: record.evidenceStatus ?? "Unknown",
    requiredEvidence: record.requiredEvidence ?? [],
    evidenceFailures: record.evidenceFailures ?? [],
    evidenceHistory: record.evidenceHistory ?? [],
    evidence: record.evidence ?? []
  });
}

async function verifySavedEvidence(record, evidenceDirectory, unknownReason, evidenceFailures, operations = {}) {
  const statFile = operations.stat ?? stat;
  const readFileContent = operations.readFile ?? readFile;
  const debugArtifact = "evidence/browser-debug.json";
  if (!(record.requiredEvidence ?? []).includes(debugArtifact)) {
    try {
      const debugFile = await statFile(join(evidenceDirectory, "browser-debug.json"));
      if (debugFile.isFile() && debugFile.size > 0) addRequiredEvidence(record, debugArtifact);
    } catch (error) {
      if (error?.code !== "ENOENT") {
        unknownReason ??= `Could not inspect saved BrowserSkill debug evidence: ${error instanceof Error ? error.message : String(error)}`;
      }
    }
  }
  const present = [];
  const invalidArtifacts = [];
  let verificationFailure = unknownReason;
  for (const evidencePath of record.requiredEvidence ?? []) {
    const fullPath = join(reportsRoot, record.runId, ...evidencePath.split("/"));
    try {
      const file = await statFile(fullPath);
      if (!file.isFile() || file.size === 0) continue;
      if (evidencePath.endsWith(".json")) {
        const document = JSON.parse(await readFileContent(fullPath, "utf8"));
        if (!document || typeof document !== "object" || !(document.run || Array.isArray(document.runs))) {
          invalidArtifacts.push(`Saved debug evidence has an invalid document: ${evidencePath}`);
          continue;
        }
      } else if (evidencePath.endsWith(".png")) {
        const image = await readFileContent(fullPath);
        if (!image.subarray(0, 8).equals(Buffer.from([137, 80, 78, 71, 13, 10, 26, 10]))) {
          invalidArtifacts.push(`Saved screenshot has an invalid PNG signature: ${evidencePath}`);
          continue;
        }
      }
      present.push(evidencePath);
    } catch (error) {
      if (error?.code === "ENOENT") continue;
      if (error instanceof SyntaxError) {
        invalidArtifacts.push(`Saved debug evidence is not valid JSON: ${evidencePath}`);
      } else {
        verificationFailure ??= `Could not verify ${evidencePath}: ${error instanceof Error ? error.message : String(error)}`;
      }
    }
  }
  updateEvidenceState(record, present, verificationFailure, [...evidenceFailures, ...invalidArtifacts]);
}

export async function bestEffortBrowserCleanup(record, cleanupFailures = [], operations = {}) {
  const run = operations.runSync ?? runSync;
  const makeDirectory = operations.mkdir ?? mkdir;
  const writeRecord = operations.atomicJson ?? atomicJson;
  const stopSession = operations.stopBrowserSession ?? stopBrowserSession;
  const evidenceFailures = [];
  const sessionId = record.browser?.sessionId;
  const evidenceDirectory = join(reportsRoot, record.runId, "evidence");
  if (record.browserPageVisited) addRequiredEvidence(record, "evidence/dashboard-final.png");
  if (!sessionId) {
    const unknownReason = record.browserPageVisited
      ? "BrowserSkill session is unavailable before required evidence could be collected"
      : null;
    await verifySavedEvidence(record, evidenceDirectory, unknownReason, evidenceFailures, operations);
    return;
  }

  let present = true;
  let evidenceUnknownReason;
  try {
    present = browserSessionPresent(record, run);
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    cleanupFailures.push(`BrowserSkill session ownership check: ${message}`);
    evidenceUnknownReason = `BrowserSkill session ownership could not be verified: ${message}`;
    if (error?.code === "BSK_INSTANCE_MISMATCH") {
      await verifySavedEvidence(record, evidenceDirectory, evidenceUnknownReason, evidenceFailures, operations);
      return;
    }
  }
  if (!present) {
    if ((!record.evidenceStatus || record.evidenceStatus === "Pending") && record.browserPageVisited) {
      const debugArtifact = join(evidenceDirectory, "browser-debug.json");
      const debugExists = await stat(debugArtifact).then(file => file.isFile() && file.size > 0).catch(() => false);
      if (!debugExists) evidenceUnknownReason = "BrowserSkill session ended before capture status could be checked";
    }
    await verifySavedEvidence(record, evidenceDirectory, evidenceUnknownReason, evidenceFailures, operations);
    return;
  }

  if (record.browserPageVisited) {
    try {
      await makeDirectory(evidenceDirectory, { recursive: true });
      const screenshot = join(evidenceDirectory, "dashboard-final.png");
      run("bsk", ["screenshot", "--session", sessionId, "--full-page", "--out", screenshot], { timeout: 30_000 });
    } catch (error) {
      evidenceFailures.push(`BrowserSkill screenshot: ${error instanceof Error ? error.message : String(error)}`);
    }
  }

  try {
    const status = parseJson(run("bsk", ["debug", "status", "--session", sessionId], {
      timeout: 15_000,
      env: { BSK_AUTO_START: "0" }
    }), "BrowserSkill debug status");
    const captureFound = hasBrowserDebugCapture(status);
    if (captureFound) {
      addRequiredEvidence(record, "evidence/browser-debug.json");
      try {
        await writeRecord(join(record.stateRoot, "run.json"), record);
      } catch (error) {
        evidenceFailures.push(`Could not persist required BrowserSkill debug evidence: ${error instanceof Error ? error.message : String(error)}`);
        evidenceUnknownReason = "The required BrowserSkill debug evidence marker could not be persisted";
      }
    }
    if (captureFound) {
      let captureStopped = !isDebugCaptureActive(status);
      if (isDebugCaptureActive(status)) {
        try {
          run("bsk", ["debug", "stop", "--session", sessionId], { timeout: 20_000, env: { BSK_AUTO_START: "0" } });
          const stoppedStatus = parseJson(run("bsk", ["debug", "status", "--session", sessionId], {
            timeout: 15_000,
            env: { BSK_AUTO_START: "0" }
          }), "BrowserSkill debug status after stop");
          captureStopped = !isDebugCaptureActive(stoppedStatus);
          if (!captureStopped) evidenceFailures.push("BrowserSkill debug capture remained active after stop");
        } catch (error) {
          evidenceFailures.push(`BrowserSkill debug stop: ${error instanceof Error ? error.message : String(error)}`);
        }
      }
      if (captureStopped) {
        try {
          await makeDirectory(evidenceDirectory, { recursive: true });
          const exportPath = join(evidenceDirectory, "browser-debug.json");
          run("bsk", ["debug", "export", "--session", sessionId, "--output", exportPath], {
            timeout: 30_000,
            env: { BSK_AUTO_START: "0" }
          });
        } catch (error) {
          evidenceFailures.push(`BrowserSkill debug export: ${error instanceof Error ? error.message : String(error)}`);
        }
      }
    }
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    evidenceUnknownReason = `BrowserSkill debug status could not be inspected: ${message}`;
    evidenceFailures.push(`BrowserSkill debug status: ${message}`);
  }

  try {
    stopSession(sessionId);
  } catch (error) {
    try {
      if (browserSessionPresent(record, run)) {
        cleanupFailures.push(`BrowserSkill session stop: ${error instanceof Error ? error.message : String(error)}`);
      }
    } catch (stateError) {
      cleanupFailures.push(`BrowserSkill session stop: ${error instanceof Error ? error.message : String(error)}; verification failed: ${stateError instanceof Error ? stateError.message : String(stateError)}`);
    }
  }

  await verifySavedEvidence(record, evidenceDirectory, evidenceUnknownReason, evidenceFailures, operations);
}

async function stopRecordedProcess(liveChild, recordedChild, label, failures) {
  if (liveChild && !liveChild.closed) {
    await stopChild(liveChild, label, failures);
    return;
  }
  if (!recordedChild?.pid) return;
  await stopVerifiedPid(
    recordedChild.pid,
    label,
    recordedChild.identity,
    recordedChild.ownerMarker,
    failures
  );
}

async function stopRecordedChildren(record, children, failures) {
  await stopRecordedProcess(children.vite, record.children?.vite, "Vite", failures);
  await stopViteListener(record, failures);
  await stopRecordedProcess(children.edge, record.children?.edge, "Edge Functions", failures);
}

async function cleanupOwnedRun(record, children) {
  const result = await cleanupOwnedResources(record, {
    cleanupBrowser: async () => {
      const failures = [];
      await bestEffortBrowserCleanup(record, failures);
      return failures;
    },
    stopProcesses: async () => {
      const failures = [];
      await stopRecordedChildren(record, children, failures);
      return failures;
    },
    stopStack: async () => {
      const expected = join(record.tempRoot, "project");
      if (
        !record.projectRoot || record.projectRoot !== expected ||
        !record.projectId?.startsWith("agent-dashboard-")
      ) {
        throw new Error("Temporary project ownership did not match the recorded run");
      }
      projectCli(record.projectRoot, ["stop", "--project-id", record.projectId, "--no-backup"], { timeout: 90_000 });
    },
    removeProject: async () => {
      if (!record.tempRoot && !record.projectRoot) return;
      if (!record.tempRoot || record.projectRoot !== join(record.tempRoot, "project")) {
        throw new Error("Temporary project directory ownership did not match the recorded run");
      }
      await rm(record.tempRoot, { recursive: true, force: true });
    },
    removeCredentials: async () => {
      if (record.stateRoot) await rm(join(record.stateRoot, "credentials.json"), { force: true });
    }
  });
  if (!record.evidenceStatus || record.evidenceStatus === "Pending") {
    updateEvidenceState(record, [], "Evidence collection did not complete");
  }
  enforceEvidenceGate(record);
  return result;
}

async function shutdown(recordPath, record, children, reason) {
  if (record.shutdownPromise) return record.shutdownPromise;
  record.shutdownPromise = (async () => {
    record.shutdownReason ??= reason;
    try {
      const latest = JSON.parse(await readFile(recordPath, "utf8"));
      if (latest.productStatus === "Fail") {
        record.productStatus = "Fail";
        record.productReason = latest.productReason ?? record.productReason;
      } else {
        record.productStatus = mergeProductStatus(record.productStatus, latest.productStatus);
        if (record.productStatus !== "Fail" && latest.productReason) record.productReason = latest.productReason;
      }
      record.browserPageVisited = mergeBrowserPageVisited(record.browserPageVisited, latest.browserPageVisited);
      record.evidence = [...new Set([...(record.evidence ?? []), ...(latest.evidence ?? [])])];
    } catch (error) {
      record.cleanupFailures = [
        ...(record.cleanupFailures ?? []),
        `Run state reload: ${error instanceof Error ? error.message : String(error)}`
      ];
      record.productStatus ??= "Unknown";
    }

    try {
      await cleanupOwnedRun(record, children);
    } catch (error) {
      record.cleanupFailures = [
        ...(record.cleanupFailures ?? []),
        `Cleanup orchestration: ${error instanceof Error ? error.message : String(error)}`
      ];
    }
    if (!record.evidenceStatus || record.evidenceStatus === "Pending") {
      updateEvidenceState(record, [], "Cleanup ended before evidence completeness could be determined");
    }
    enforceEvidenceGate(record);
    record.cleanupFailures = [...new Set(record.cleanupFailures ?? [])];
    record.cleanupStatus = record.cleanupFailures.length ? "Failed" : "Succeeded";
    record.finishedAt = new Date().toISOString();
    try {
      await atomicJson(recordPath, record);
    } catch (error) {
      record.cleanupFailures.push(`Run state write: ${error instanceof Error ? error.message : String(error)}`);
      record.cleanupStatus = "Failed";
    }
    try {
      await publishReport(record);
    } catch (error) {
      record.cleanupFailures.push(`Report write: ${error instanceof Error ? error.message : String(error)}`);
      record.cleanupStatus = "Failed";
      await atomicJson(recordPath, record).catch(() => undefined);
    }
    process.exitCode = record.cleanupStatus === "Succeeded" ? 0 : 1;
  })();
  return record.shutdownPromise;
}

async function preflightPorts() {
  const values = await reservePorts(10);
  return {
    api: values[0], db: values[1], shadow: values[2], studio: values[3], mailpit: values[4],
    smtp: values[5], pop3: values[6], analytics: values[7], vector: values[8], vite: values[9]
  };
}

function statusFor(projectRootPath) {
  return parseJson(projectCli(projectRootPath, ["status", "--output", "json"]), "Temporary Supabase status");
}

async function start(args) {
  const options = parseArgs(args);
  if (options["--scenario"] !== "dashboard" || !options["--browser"]) {
    throw new Error("Usage: pnpm test:agent:start -- --scenario dashboard --browser <connected-instance-id>");
  }

  const runId = randomUUID();
  const projectId = `agent-dashboard-${randomBytes(8).toString("hex")}`;
  const tempRoot = join(stateRoot, runId, "stack");
  const statePath = join(stateRoot, runId);
  const projectRootPath = join(tempRoot, "project");
  const recordPath = join(statePath, "run.json");
  const startedAt = new Date().toISOString();
  const record = {
    schemaVersion: 1,
    runId,
    scenario: "dashboard",
    commit: runSync("git", ["rev-parse", "HEAD"]).trim(),
    browser: null,
    appOrigin: null,
    startedAt,
    supervisor: { pid: process.pid, identity: identityFor(process.pid), command: process.argv.join(" "), cwd: process.cwd() },
    stateRoot: statePath,
    tempRoot,
    projectRoot: projectRootPath,
    projectId,
    ports: null,
    productStatus: "Unknown",
    productReason: null,
    evidence: [],
    evidenceStatus: "Pending",
    requiredEvidence: [],
    evidenceFailures: [],
    cleanupFailures: [],
    stackMayExist: false,
    stackStarted: false
  };
  const children = { vite: undefined, edge: undefined };
  let browser;
  let admin;
  let credentials;
  let finishSupervisor;
  const supervisorFinished = new Promise(resolveFinished => {
    finishSupervisor = resolveFinished;
  });
  const lifecycle = createStartupLifecycle(reason => {
    void shutdown(recordPath, record, children, reason).finally(() => finishSupervisor());
  });
  const onSigint = () => { void lifecycle.requestShutdown("SIGINT"); };
  const onSigterm = () => { void lifecycle.requestShutdown("SIGTERM"); };
  const onUncaughtException = error => {
    record.failure = redact(error instanceof Error ? error.stack ?? error.message : String(error));
    void lifecycle.requestShutdown("uncaughtException");
  };
  const onUnhandledRejection = error => {
    record.failure = redact(error instanceof Error ? error.stack ?? error.message : String(error));
    void lifecycle.requestShutdown("unhandledRejection");
  };
  process.on("SIGINT", onSigint);
  process.on("SIGTERM", onSigterm);
  process.on("uncaughtException", onUncaughtException);
  process.on("unhandledRejection", onUnhandledRejection);

  try {
    console.log(`Starting isolated Dashboard scenario ${runId}.`);
    await startupStage(lifecycle, () => mkdir(statePath, { recursive: true, mode: 0o700 }));
    await startupStage(lifecycle, () => chmod(statePath, 0o700));
    await startupStage(lifecycle, () => atomicJson(recordPath, record));

    lifecycle.throwIfCancelled();
    browser = preflightBrowser(options["--browser"]);
    record.browser = {
      instanceId: browser.browserId,
      sessionId: browser.sessionId,
      daemonVersion: browser.daemonVersion,
      browserVersion: browser.browserVersion,
      extensionVersion: browser.extensionVersion
    };
    await atomicJson(recordPath, record);
    await startupCheckpoint(lifecycle);

    await startupStage(lifecycle, () => preflightDocker());
    const ports = await startupStage(lifecycle, () => preflightPorts());
    record.ports = ports;
    const appOrigin = `http://127.0.0.1:${ports.vite}`;
    record.appOrigin = appOrigin;
    await startupStage(lifecycle, () => atomicJson(recordPath, record));

    await startupStage(lifecycle, () => mkdir(tempRoot, { recursive: true, mode: 0o700 }));
    await startupStage(lifecycle, () => createIsolatedProject(tempRoot, projectId, ports, { appOrigin }));
    const edgeEnvPath = join(statePath, "edge.env");
    await startupStage(lifecycle, () => writeFile(edgeEnvPath, `APP_ALLOWED_ORIGINS=${appOrigin}\n`, { mode: 0o600 }));
    await startupStage(lifecycle, () => chmod(edgeEnvPath, 0o600));

    await startupStage(lifecycle, () => startOwnedStack(
      record,
      () => atomicJson(recordPath, record),
      () => projectCli(projectRootPath, ["start"], { timeout: 240_000 }),
      () => startupCheckpoint(lifecycle)
    ));
    record.stackStarted = true;
    await startupStage(lifecycle, () => atomicJson(recordPath, record));
    await startupStage(lifecycle, () => projectCli(projectRootPath, ["db", "reset", "--local"], { timeout: 240_000 }));
    const status = await startupStage(lifecycle, () => statusFor(projectRootPath));
    const local = assertLocalStatus(status);
    record.apiUrl = local.apiUrl;

    const supabaseCommand = process.platform === "win32" ? "cmd.exe" : "pnpm";
    const supabaseArgs = process.platform === "win32"
      ? ["/d", "/s", "/c", join(frontendRoot, "node_modules", ".bin", "supabase.cmd"), "--workdir", projectRootPath, "functions", "serve", "--env-file", edgeEnvPath]
      : ["--filter", "fullstack-admin-frontend", "exec", "supabase", "--workdir", projectRootPath, "functions", "serve", "--env-file", edgeEnvPath];
    lifecycle.throwIfCancelled();
    children.edge = spawnManaged(supabaseCommand, supabaseArgs, {
      cwd: projectRoot,
      logPath: join(statePath, "edge.log"),
      runId
    });
    record.children = {
      edge: {
        pid: children.edge.pid,
        identity: identityFor(children.edge.pid),
        ownerMarker: projectRootPath,
        command: children.edge.spawnfile,
        args: children.edge.spawnargs,
        cwd: projectRootPath
      }
    };
    await atomicJson(recordPath, record);
    await startupCheckpoint(lifecycle);

    lifecycle.throwIfCancelled();
    children.vite = spawnManaged(pnpm, [
      "--filter", "fullstack-admin-frontend", "exec", "vite", "--host", "127.0.0.1", "--port", String(ports.vite), "--strictPort"
    ], {
      cwd: projectRoot,
      logPath: join(statePath, "vite.log"),
      runId,
      env: {
        VITE_PORT: String(ports.vite),
        VITE_PUBLIC_PATH: "/",
        VITE_ROUTER_HISTORY: "hash",
        VITE_SUPABASE_URL: local.apiUrl,
        VITE_SUPABASE_PUBLISHABLE_KEY: local.publishableKey
      }
    });
    record.children.vite = {
      pid: children.vite.pid,
      identity: identityFor(children.vite.pid),
      ownerMarker: viteProcessOwnerMarkers(ports.vite),
      command: children.vite.spawnfile,
      args: children.vite.spawnargs,
      cwd: projectRoot
    };
    await atomicJson(recordPath, record);
    await startupCheckpoint(lifecycle);

    await startupStage(lifecycle, () => runCancellableStartupChecks([
      abortSignal => poll(children.edge, "Edge Functions process", () => {
        const identity = identityFor(children.edge.pid);
        if (!identity) return false;
        record.children.edge.identity = identity;
        return true;
      }, 10_000, lifecycle, abortSignal),
      abortSignal => poll(children.vite, "Vite process", () => {
        const identity = identityFor(children.vite.pid);
        if (!identity) return false;
        record.children.vite.identity = identity;
        return true;
      }, 10_000, lifecycle, abortSignal)
    ]));
    await startupStage(lifecycle, () => atomicJson(recordPath, record));
    await startupStage(lifecycle, () => runCancellableStartupChecks([
      abortSignal => waitForEdge(children.edge, local.apiUrl, local.publishableKey, appOrigin, lifecycle, abortSignal),
      abortSignal => waitForApp(children.vite, appOrigin, lifecycle, abortSignal)
    ]));

    const viteListeners = listeningPids(ports.vite)
      .map(pid => ({ pid, identity: identityFor(pid) }))
      .filter(listener => listener.identity?.includes(`--port ${ports.vite}`) && listener.identity.includes(frontendRoot));
    if (viteListeners.length !== 1) throw new Error("Vite port ownership could not be verified for this run");
    record.children.viteListener = {
      ...viteListeners[0],
      ownerMarker: viteListenerOwnerMarkers(ports.vite, frontendRoot),
      cwd: frontendRoot
    };
    await startupStage(lifecycle, () => atomicJson(recordPath, record));

    await startupStage(lifecycle, () => runSync(pnpm, ["setup:admin"], {
      cwd: projectRoot,
      env: { SUPABASE_PROJECT_ROOT: projectRootPath },
      timeout: 60_000
    }));
    admin = createClient(local.apiUrl, local.serviceRoleKey, {
      auth: { autoRefreshToken: false, persistSession: false }
    });
    credentials = { runId };
    await startupStage(lifecycle, () => writeFile(join(statePath, "credentials.json"), "{}", { mode: 0o600 }));
    const login = await startupStage(lifecycle, () => provisionAgentFixture(admin, runId, credentials));
    await startupStage(lifecycle, () => writeFile(join(statePath, "credentials.json"), `${JSON.stringify(login)}\n`, { mode: 0o600 }));
    await startupStage(lifecycle, () => chmod(join(statePath, "credentials.json"), 0o600));
    credentials.runId = runId;
    credentials.loginName = login.loginName;
    const checked = await startupStage(lifecycle, () => verifyCallerAccess({
      apiUrl: local.apiUrl,
      publishableKey: local.publishableKey,
      origin: appOrigin,
      credentials,
      password: login.password
    }));
    record.fixture = {
      authUserId: login.authUserId,
      profileId: login.profileId,
      messageId: credentials.messageId,
      operationId: credentials.operationId,
      operationMarker: credentials.operationMarker,
      loginName: login.loginName
    };
    record.evidence.push(
      `readiness:registered-caller-session`,
      `readiness:dashboard-overview:${checked.overview.todoCount} todos`,
      "readiness:navigation:dashboard-and-messages",
      "readiness:message-read-model:caller-scoped"
    );
    admin.realtime.disconnect();
    admin = undefined;
    record.readiness = "Passed";
    await startupStage(lifecycle, () => atomicJson(recordPath, record));

    console.log(JSON.stringify({
      status: "READY",
      runId,
      scenario: "dashboard",
      browserInstanceId: browser.browserId,
      browserSessionId: browser.sessionId,
      appOrigin,
      loginName: login.loginName,
      reportPath: reportPath(runId)
    }));
    lifecycle.markReady();
    await supervisorFinished;
  } catch (error) {
    admin?.realtime.disconnect();
    record.failure = redact(error instanceof Error ? error.stack ?? error.message : String(error));
    record.productReason = lifecycle.cancelled
      ? `Dashboard startup cancelled (${lifecycle.reason})`
      : "Dashboard readiness or temporary environment startup failed";
    record.productStatus = "Unknown";
    await atomicJson(recordPath, record).catch(() => undefined);
    await shutdown(recordPath, record, children, lifecycle.reason ?? "startup-failed");
    finishSupervisor();
    throw new Error(`Dashboard scenario did not become READY (run ${runId})`, { cause: error });
  } finally {
    process.off("SIGINT", onSigint);
    process.off("SIGTERM", onSigterm);
    process.off("uncaughtException", onUncaughtException);
    process.off("unhandledRejection", onUnhandledRejection);
  }
}

async function persistCleanupResult(recordPath, record) {
  if (!record.evidenceStatus || record.evidenceStatus === "Pending") {
    updateEvidenceState(record, [], "Cleanup ended before evidence completeness could be determined");
  }
  enforceEvidenceGate(record);
  record.cleanupFailures = [...new Set(record.cleanupFailures ?? [])];
  record.cleanupStatus = record.cleanupFailures.length ? "Failed" : "Succeeded";
  record.finishedAt ??= new Date().toISOString();
  try {
    await atomicJson(recordPath, record);
  } catch (error) {
    record.cleanupFailures.push(`Run state write: ${error instanceof Error ? error.message : String(error)}`);
    record.cleanupStatus = "Failed";
  }
  try {
    await publishReport(record);
  } catch (error) {
    record.cleanupFailures.push(`Report write: ${error instanceof Error ? error.message : String(error)}`);
    record.cleanupStatus = "Failed";
    await atomicJson(recordPath, record).catch(() => undefined);
  }
  return record.cleanupStatus;
}

async function cleanup(args) {
  const options = parseArgs(args);
  const runId = safeRunId(options["--run-id"]);
  const requestedStatus = options["--product-status"];
  if (options["--browser-page-visited"] !== undefined && options["--browser-page-visited"] !== "true") {
    throw new Error("--browser-page-visited accepts only true when the app page was inspected");
  }
  if (requestedStatus && !["Pass", "Fail", "Unknown"].includes(requestedStatus)) {
    throw new Error("--product-status must be Pass, Fail, or Unknown");
  }

  const { recordPath, record } = await readRun(runId);
  if (options["--browser-page-visited"] === "true") record.browserPageVisited = true;
  const previousStatus = record.productStatus;
  record.productStatus = mergeProductStatus(previousStatus, requestedStatus);
  if (options["--reason"] && !(previousStatus === "Fail" && requestedStatus !== "Fail")) {
    record.productReason = options["--reason"];
  }
  await atomicJson(recordPath, record);

  const supervisorIdentity = record.supervisor?.identity;
  const currentIdentity = record.supervisor?.pid ? identityFor(record.supervisor.pid) : null;
  const supervisorMode = supervisorCleanupMode(supervisorIdentity, currentIdentity, record.finishedAt);

  if (supervisorMode === "wait") {
    const exited = await waitForIdentityChange(record.supervisor.pid, supervisorIdentity, 30_000);
    if (!exited) {
      record.cleanupFailures = [
        ...(record.cleanupFailures ?? []),
        "Completed Dashboard supervisor did not exit; orphan cleanup was deferred to avoid racing it"
      ];
      await persistCleanupResult(recordPath, record);
      throw new Error(`Supervisor did not exit for run ${runId}`);
    }
  } else if (supervisorMode === "signal") {
    if (!currentIdentity.includes("scripts/agent-testing.mjs start")) {
      throw new Error("Recorded supervisor command did not match this test runner");
    }
    try {
      signalManagedProcess(record.supervisor.pid, "SIGTERM");
    } catch (error) {
      if (identityFor(record.supervisor.pid) === supervisorIdentity) throw error;
    }
    const exited = await waitForIdentityChange(record.supervisor.pid, supervisorIdentity, 180_000);
    if (!exited) {
      record.cleanupFailures = [
        ...(record.cleanupFailures ?? []),
        "Dashboard supervisor did not exit after SIGTERM; no orphan cleanup was run concurrently"
      ];
      await persistCleanupResult(recordPath, record);
      throw new Error(`Supervisor did not exit for run ${runId}`);
    }
  }

  const latest = await readRun(runId);
  const finalRecord = latest.record;
  await stopOrphan(finalRecord);
  const cleanupStatus = await persistCleanupResult(latest.recordPath, finalRecord);
  console.log(JSON.stringify({
    runId,
    productStatus: finalRecord.productStatus ?? "Unknown",
    cleanupStatus,
    reportPath: reportPath(runId),
    retainedProjectRoot: finalRecord.retainedProjectRoot ?? null
  }));
  if (cleanupStatus !== "Succeeded") throw new Error(`Cleanup failed for run ${runId}`);
}

async function stopOrphan(record) {
  return await cleanupOwnedRun(record, { vite: undefined, edge: undefined });
}

async function fillCredential(args) {
  const options = parseArgs(args);
  const { root, record } = await readRun(safeRunId(options["--run-id"]));
  const field = options["--field"];
  const sessionId = options["--session"];
  const reference = options["--ref"];
  if (!sessionId || !reference || !["loginName", "password"].includes(field)) {
    throw new Error("Usage: node scripts/agent-testing.mjs fill --run-id <id> --session <id> --ref <element-ref> --field loginName|password");
  }
  if (sessionId !== record.browser?.sessionId) throw new Error("BrowserSkill Session does not belong to this run");
  const credentials = JSON.parse(await readFile(join(root, "credentials.json"), "utf8"));
  const value = credentials[field];
  if (typeof value !== "string" || !value) throw new Error("Requested temporary credential is unavailable");
  runSync("bsk", ["fill", reference, "--value", value, "--session", sessionId], {
    timeout: 20_000,
    env: { BSK_AUTO_START: "0" }
  });
}

async function main() {
  const [command, ...args] = process.argv.slice(2);
  if (command === "start") return await start(args);
  if (command === "cleanup") return await cleanup(args);
  if (command === "fill") return await fillCredential(args);
  throw new Error("Usage: node scripts/agent-testing.mjs <start|cleanup|fill> ...");
}

const invokedPath = process.argv[1] ? pathToFileURL(resolve(process.argv[1])).href : "";
if (invokedPath === import.meta.url) {
  main().catch(error => {
    process.stderr.write(`${redact(error instanceof Error ? error.stack ?? error.message : String(error))}\n`);
    process.exitCode = 1;
  });
}
