insert into public.permission_catalog (permission_key, description)
values ('audit.logs.read', '读取已授权的登录、操作与异常日志')
on conflict (permission_key) do update
set description = excluded.description;

create table public.login_logs (
  id bigint generated by default as identity primary key,
  user_id bigint references public.profiles (id) on delete set null,
  login_name text not null check (length(trim(login_name)) between 1 and 64),
  login_ip text check (login_ip is null or length(login_ip) <= 64),
  user_agent text check (user_agent is null or length(user_agent) <= 512),
  login_result smallint not null check (login_result in (0, 1)),
  failure_reason text check (failure_reason is null or length(failure_reason) <= 255),
  logged_at timestamptz not null default now()
);

create table public.operation_logs (
  id bigint generated by default as identity primary key,
  operator_id bigint references public.profiles (id) on delete set null,
  operator_name text check (operator_name is null or length(operator_name) <= 128),
  module_code text not null check (length(trim(module_code)) between 1 and 64),
  operation_type text not null check (length(trim(operation_type)) between 1 and 32),
  request_method text not null check (length(trim(request_method)) between 1 and 16),
  request_path text not null check (length(trim(request_path)) between 1 and 255),
  request_params jsonb,
  operation_result smallint not null check (operation_result in (0, 1)),
  error_message text,
  operated_at timestamptz not null default now()
);

create table public.exception_logs (
  id bigint generated by default as identity primary key,
  request_path text not null check (length(trim(request_path)) between 1 and 255),
  request_method text not null check (length(trim(request_method)) between 1 and 16),
  error_type text not null check (length(trim(error_type)) between 1 and 128),
  error_message text not null,
  stack_summary text,
  handled_status smallint not null default 0 check (handled_status in (0, 1)),
  occurred_at timestamptz not null default now()
);

create index login_logs_recent_idx on public.login_logs (logged_at desc, id desc);
create index login_logs_name_recent_idx on public.login_logs (lower(login_name), logged_at desc);
create index operation_logs_recent_idx on public.operation_logs (operated_at desc, id desc);
create index operation_logs_operator_recent_idx on public.operation_logs (operator_id, operated_at desc);
create index operation_logs_module_recent_idx on public.operation_logs (module_code, operation_type, operated_at desc);
create index exception_logs_recent_idx on public.exception_logs (occurred_at desc, id desc);
create index exception_logs_handled_recent_idx on public.exception_logs (handled_status, occurred_at desc);

comment on table public.login_logs is 'Account/password login attempts; passwords and tokens are never stored.';
comment on table public.operation_logs is 'Successful mutations performed by registered password sessions and authorized server actions.';
comment on table public.exception_logs is 'Sanitized server-side failures; stack summaries must not contain credentials or request secrets.';

alter table public.login_logs enable row level security;
alter table public.operation_logs enable row level security;
alter table public.exception_logs enable row level security;

revoke all on public.login_logs, public.operation_logs, public.exception_logs
  from public, anon, authenticated;
grant select on public.login_logs, public.operation_logs, public.exception_logs to authenticated;
grant all on public.login_logs, public.operation_logs, public.exception_logs to service_role;
grant usage, select on sequence public.login_logs_id_seq,
  public.operation_logs_id_seq, public.exception_logs_id_seq to service_role;

create policy login_logs_read_authorized
on public.login_logs for select to authenticated
using (
  (select app_private.is_password_authenticated())
  and (select app_private.has_permission('audit.logs.read'))
);

create policy operation_logs_read_authorized
on public.operation_logs for select to authenticated
using (
  (select app_private.is_password_authenticated())
  and (select app_private.has_permission('audit.logs.read'))
);

create policy exception_logs_read_authorized
on public.exception_logs for select to authenticated
using (
  (select app_private.is_password_authenticated())
  and (select app_private.has_permission('audit.logs.read'))
);

create view public.login_log_read_model
with (security_invoker = true)
as
select
  id::text as id,
  user_id::text as user_id,
  login_name,
  login_ip,
  user_agent,
  login_result,
  failure_reason,
  logged_at
from public.login_logs;

create view public.operation_log_read_model
with (security_invoker = true)
as
select
  id::text as id,
  operator_id::text as operator_id,
  operator_name,
  module_code,
  operation_type,
  request_method,
  request_path,
  request_params,
  operation_result,
  error_message,
  operated_at
from public.operation_logs;

create view public.exception_log_read_model
with (security_invoker = true)
as
select
  id::text as id,
  request_path,
  request_method,
  error_type,
  error_message,
  stack_summary,
  handled_status,
  occurred_at
from public.exception_logs;

revoke all on public.login_log_read_model, public.operation_log_read_model,
  public.exception_log_read_model from public, anon;
grant select on public.login_log_read_model, public.operation_log_read_model,
  public.exception_log_read_model to authenticated;

create function app_private.log_current_mutation()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  actor_id bigint;
  actor_name text;
  row_data jsonb;
  row_id text;
  module_key text;
  operation_key text;
  method_key text;
begin
  if not (select app_private.is_password_authenticated()) then
    if tg_op = 'DELETE' then return old; else return new; end if;
  end if;

  actor_id := (select public.current_business_user_id())::bigint;
  if actor_id is null then
    if tg_op = 'DELETE' then return old; else return new; end if;
  end if;

  if tg_op = 'DELETE' then
    row_data := to_jsonb(old);
  else
    row_data := to_jsonb(new);
  end if;
  row_id := coalesce(
    row_data ->> 'id',
    nullif(concat_ws(':', row_data ->> 'user_id', row_data ->> 'role_id'), ''),
    'unknown'
  );

  module_key := case tg_table_name
    when 'profiles' then 'USER'
    when 'user_roles' then 'USER_ROLE'
    when 'roles' then 'ROLE'
    when 'role_permissions' then 'ROLE_PERMISSION'
    when 'menus' then 'MENU'
    when 'departments' then 'DEPARTMENT'
    when 'posts' then 'POST'
    when 'dict_types' then 'DICTIONARY_TYPE'
    when 'dict_items' then 'DICTIONARY_ITEM'
    when 'system_configs' then 'SYSTEM_CONFIG'
    when 'messages' then 'MESSAGE'
    when 'attachments' then 'ATTACHMENT'
    else upper(tg_table_name)
  end;
  operation_key := case tg_op
    when 'INSERT' then 'CREATE'
    when 'UPDATE' then 'UPDATE'
    when 'DELETE' then 'DELETE'
  end;
  method_key := case tg_op
    when 'INSERT' then 'POST'
    when 'UPDATE' then 'PATCH'
    when 'DELETE' then 'DELETE'
  end;

  select profile.display_name into actor_name
  from public.profiles as profile
  where profile.id = actor_id;

  insert into public.operation_logs (
    operator_id, operator_name, module_code, operation_type,
    request_method, request_path, request_params, operation_result
  ) values (
    actor_id,
    actor_name,
    module_key,
    operation_key,
    method_key,
    '/rest/v1/' || tg_table_name,
    jsonb_build_object('recordId', row_id),
    1
  );

  if tg_op = 'DELETE' then return old; else return new; end if;
end;
$$;

revoke all on function app_private.log_current_mutation() from public, anon, authenticated, service_role;

create trigger audit_profiles_mutation after insert or update or delete on public.profiles
for each row execute function app_private.log_current_mutation();
create trigger audit_user_roles_mutation after insert or update or delete on public.user_roles
for each row execute function app_private.log_current_mutation();
create trigger audit_roles_mutation after insert or update or delete on public.roles
for each row execute function app_private.log_current_mutation();
create trigger audit_role_permissions_mutation after insert or update or delete on public.role_permissions
for each row execute function app_private.log_current_mutation();
create trigger audit_menus_mutation after insert or update or delete on public.menus
for each row execute function app_private.log_current_mutation();
create trigger audit_departments_mutation after insert or update or delete on public.departments
for each row execute function app_private.log_current_mutation();
create trigger audit_posts_mutation after insert or update or delete on public.posts
for each row execute function app_private.log_current_mutation();
create trigger audit_dict_types_mutation after insert or update or delete on public.dict_types
for each row execute function app_private.log_current_mutation();
create trigger audit_dict_items_mutation after insert or update or delete on public.dict_items
for each row execute function app_private.log_current_mutation();
create trigger audit_system_configs_mutation after insert or update or delete on public.system_configs
for each row execute function app_private.log_current_mutation();
create trigger audit_messages_mutation after insert or update or delete on public.messages
for each row execute function app_private.log_current_mutation();
create trigger audit_attachments_mutation after insert or update or delete on public.attachments
for each row execute function app_private.log_current_mutation();

create function public.record_login_attempt(
  p_login_name text,
  p_user_id bigint,
  p_login_ip text,
  p_user_agent text,
  p_login_result smallint,
  p_failure_reason text
)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
begin
  if nullif(trim(p_login_name), '') is null
     or length(p_login_name) > 64
     or (p_login_ip is not null and length(p_login_ip) > 64)
     or (p_user_agent is not null and length(p_user_agent) > 512)
     or p_login_result not in (0, 1)
     or (p_failure_reason is not null and length(p_failure_reason) > 255)
     or (p_login_result = 1 and p_user_id is null) then
    raise exception using errcode = '22023', message = 'Login audit event is invalid';
  end if;
  if p_user_id is not null and not exists (
    select 1 from public.profiles as profile where profile.id = p_user_id
  ) then
    raise exception using errcode = '23503', message = 'Login audit user does not exist';
  end if;

  insert into public.login_logs (
    user_id, login_name, login_ip, user_agent, login_result, failure_reason
  ) values (
    p_user_id, trim(p_login_name), p_login_ip, p_user_agent, p_login_result,
    case when p_login_result = 1 then null else left(p_failure_reason, 255) end
  );
  return true;
end;
$$;

revoke all on function public.record_login_attempt(text, bigint, text, text, smallint, text)
  from public, anon, authenticated;
grant execute on function public.record_login_attempt(text, bigint, text, text, smallint, text)
  to service_role;

create function public.record_exception_event(
  p_request_path text,
  p_request_method text,
  p_error_type text,
  p_error_message text,
  p_stack_summary text
)
returns text
language plpgsql
security definer
set search_path = ''
as $$
declare
  exception_id bigint;
begin
  if nullif(trim(p_request_path), '') is null
     or length(p_request_path) > 255
     or nullif(trim(p_request_method), '') is null
     or length(p_request_method) > 16
     or nullif(trim(p_error_type), '') is null
     or length(p_error_type) > 128
     or nullif(trim(p_error_message), '') is null then
    raise exception using errcode = '22023', message = 'Exception audit event is invalid';
  end if;

  insert into public.exception_logs (
    request_path, request_method, error_type, error_message, stack_summary
  ) values (
    left(p_request_path, 255), left(p_request_method, 16), left(p_error_type, 128),
    left(p_error_message, 3000), left(p_stack_summary, 3000)
  ) returning id into exception_id;
  return exception_id::text;
end;
$$;

revoke all on function public.record_exception_event(text, text, text, text, text)
  from public, anon, authenticated;
grant execute on function public.record_exception_event(text, text, text, text, text)
  to service_role;

create function public.record_operation_event(
  p_operator_id bigint,
  p_module_code text,
  p_operation_type text,
  p_request_method text,
  p_request_path text,
  p_request_params jsonb
)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  operator_name_snapshot text;
begin
  if p_operator_id is null
     or nullif(trim(p_module_code), '') is null
     or length(p_module_code) > 64
     or nullif(trim(p_operation_type), '') is null
     or length(p_operation_type) > 32
     or nullif(trim(p_request_method), '') is null
     or length(p_request_method) > 16
     or nullif(trim(p_request_path), '') is null
     or length(p_request_path) > 255
     or (p_request_params is not null and (
       jsonb_typeof(p_request_params) <> 'object'
       or pg_column_size(p_request_params) > 3000
     )) then
    raise exception using errcode = '22023', message = 'Operation audit event is invalid';
  end if;

  select profile.display_name into operator_name_snapshot
  from public.profiles as profile
  where profile.id = p_operator_id;
  if not found then
    raise exception using errcode = '23503', message = 'Operation audit actor does not exist';
  end if;

  insert into public.operation_logs (
    operator_id, operator_name, module_code, operation_type,
    request_method, request_path, request_params, operation_result
  ) values (
    p_operator_id, operator_name_snapshot, trim(p_module_code), trim(p_operation_type),
    upper(trim(p_request_method)), trim(p_request_path), p_request_params, 1
  );
  return true;
end;
$$;

revoke all on function public.record_operation_event(bigint, text, text, text, text, jsonb)
  from public, anon, authenticated;
grant execute on function public.record_operation_event(bigint, text, text, text, text, jsonb)
  to service_role;

comment on function public.record_login_attempt(text, bigint, text, text, smallint, text) is
  'Service-role-only writer for account/password login outcomes; no credentials or tokens are accepted.';
comment on function public.record_exception_event(text, text, text, text, text) is
  'Service-role-only writer for sanitized server exceptions.';
comment on function public.record_operation_event(bigint, text, text, text, text, jsonb) is
  'Service-role-only writer for minimal, redacted operations performed by trusted Edge Functions.';
