-- Organization management slice: preserve business BIGINTs and profile references.
-- Existing profile mappings are intentionally not validated in this rollout.
insert into public.permission_catalog (permission_key, description)
values
  ('organization.departments.read', '读取部门'),
  ('organization.departments.create', '创建部门'),
  ('organization.departments.update', '更新部门'),
  ('organization.departments.delete', '删除未被用户引用的部门'),
  ('organization.posts.read', '读取岗位'),
  ('organization.posts.create', '创建岗位'),
  ('organization.posts.update', '更新岗位'),
  ('organization.posts.delete', '删除未被用户引用的岗位')
on conflict (permission_key) do update
set description = excluded.description;

create table public.departments (
  id bigint generated by default as identity primary key,
  dept_code text not null
    check (dept_code = btrim(dept_code) and length(dept_code) between 1 and 64),
  dept_name text not null
    check (dept_name = btrim(dept_name) and length(dept_name) between 1 and 128),
  status smallint not null default 1 check (status in (0, 1)),
  description text
    check (description is null or length(description) <= 255),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted boolean not null default false
);
create unique index departments_dept_code_lower_uidx
  on public.departments (lower(dept_code));
create index departments_status_deleted_idx
  on public.departments (status, deleted, id);

create table public.posts (
  id bigint generated by default as identity primary key,
  post_code text not null
    check (post_code = btrim(post_code) and length(post_code) between 1 and 64),
  post_name text not null
    check (post_name = btrim(post_name) and length(post_name) between 1 and 128),
  status smallint not null default 1 check (status in (0, 1)),
  description text
    check (description is null or length(description) <= 255),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted boolean not null default false
);
create unique index posts_post_code_lower_uidx
  on public.posts (lower(post_code));
create index posts_status_deleted_idx
  on public.posts (status, deleted, id);

comment on table public.departments is
  'Department directory. BIGINT IDs retain the legacy users.dept_id mapping.';
comment on table public.posts is
  'Post directory. BIGINT IDs retain the legacy users.post_id mapping.';
comment on column public.profiles.department_id is
  'Legacy-compatible department BIGINT; source rows are imported before FK validation.';
comment on column public.profiles.post_id is
  'Legacy-compatible post BIGINT; source rows are imported before FK validation.';

-- NOT VALID keeps existing profile rows intact while enforcing every new or
-- changed reference. The source directory rows must be imported before new
-- profile assignments can reference their IDs.
alter table public.profiles
  add constraint profiles_department_id_fkey
    foreign key (department_id) references public.departments (id)
    on delete restrict not valid,
  add constraint profiles_post_id_fkey
    foreign key (post_id) references public.posts (id)
    on delete restrict not valid;

-- Prevent authenticated profile managers from assigning a newly changed
-- reference to a soft-deleted directory row. Trusted service-role imports may
-- preserve an existing legacy reference after their ID has been preflighted.
create function app_private.guard_profile_organization_assignments()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  caller_role text := auth.jwt()->>'role';
begin
  if caller_role = 'service_role' then
    return new;
  end if;

  if tg_op = 'INSERT' then
    if new.department_id is not null then
      perform 1 from public.departments as department
      where department.id = new.department_id and not department.deleted
      for key share;
      if not found then
        raise exception using errcode = '23503', message = 'Department is missing or soft-deleted';
      end if;
    end if;
    if new.post_id is not null then
      perform 1 from public.posts as post
      where post.id = new.post_id and not post.deleted
      for key share;
      if not found then
        raise exception using errcode = '23503', message = 'Post is missing or soft-deleted';
      end if;
    end if;
  else
    if new.department_id is distinct from old.department_id and new.department_id is not null then
      perform 1 from public.departments as department
      where department.id = new.department_id and not department.deleted
      for key share;
      if not found then
        raise exception using errcode = '23503', message = 'Department is missing or soft-deleted';
      end if;
    end if;
    if new.post_id is distinct from old.post_id and new.post_id is not null then
      perform 1 from public.posts as post
      where post.id = new.post_id and not post.deleted
      for key share;
      if not found then
        raise exception using errcode = '23503', message = 'Post is missing or soft-deleted';
      end if;
    end if;
  end if;
  return new;
end;
$$;
revoke all on function app_private.guard_profile_organization_assignments()
  from public, anon, authenticated, service_role;

create trigger profiles_guard_organization_assignments
before insert or update of department_id, post_id on public.profiles
for each row execute function app_private.guard_profile_organization_assignments();

create trigger departments_touch_updated_at
before update on public.departments
for each row execute function app_private.touch_updated_at();
create trigger posts_touch_updated_at
before update on public.posts
for each row execute function app_private.touch_updated_at();

create view public.department_read_model
with (security_invoker = true)
as
select
  department.id::text as id,
  department.dept_code,
  department.dept_name,
  department.status,
  department.description,
  department.created_at,
  department.updated_at
from public.departments as department
where not department.deleted;

create view public.post_read_model
with (security_invoker = true)
as
select
  post.id::text as id,
  post.post_code,
  post.post_name,
  post.status,
  post.description,
  post.created_at,
  post.updated_at
from public.posts as post
where not post.deleted;

alter table public.departments enable row level security;
alter table public.posts enable row level security;

create policy departments_read
on public.departments for select to authenticated
using (
  not deleted
  and (select app_private.is_password_authenticated())
  and (select app_private.has_permission('organization.departments.read'))
);

create policy departments_create
on public.departments for insert to authenticated
with check (
  not deleted
  and (select app_private.is_password_authenticated())
  and (select app_private.has_permission('organization.departments.create'))
);

create policy departments_update
on public.departments for update to authenticated
using (
  not deleted
  and (select app_private.is_password_authenticated())
  and (select app_private.has_permission('organization.departments.update'))
)
with check (
  not deleted
  and (select app_private.is_password_authenticated())
  and (select app_private.has_permission('organization.departments.update'))
);

create policy posts_read
on public.posts for select to authenticated
using (
  not deleted
  and (select app_private.is_password_authenticated())
  and (select app_private.has_permission('organization.posts.read'))
);

create policy posts_create
on public.posts for insert to authenticated
with check (
  not deleted
  and (select app_private.is_password_authenticated())
  and (select app_private.has_permission('organization.posts.create'))
);

create policy posts_update
on public.posts for update to authenticated
using (
  not deleted
  and (select app_private.is_password_authenticated())
  and (select app_private.has_permission('organization.posts.update'))
)
with check (
  not deleted
  and (select app_private.is_password_authenticated())
  and (select app_private.has_permission('organization.posts.update'))
);

revoke all on public.departments, public.posts,
  public.department_read_model, public.post_read_model
  from public, anon, authenticated;

grant select on public.departments, public.posts to authenticated;
grant insert (dept_code, dept_name, status, description)
  on public.departments to authenticated;
grant update (dept_code, dept_name, status, description)
  on public.departments to authenticated;
grant insert (post_code, post_name, status, description)
  on public.posts to authenticated;
grant update (post_code, post_name, status, description)
  on public.posts to authenticated;
grant usage, select on sequence public.departments_id_seq, public.posts_id_seq
  to authenticated;
grant select on public.department_read_model, public.post_read_model
  to authenticated;

create function public.delete_department(p_department_id text)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  target_id bigint;
begin
  if not app_private.is_password_authenticated()
    or not app_private.has_permission('organization.departments.delete') then
    raise exception using errcode = '42501', message = 'Department delete permission is required';
  end if;
  if p_department_id is null or p_department_id !~ '^[1-9][0-9]*$' then
    raise exception using errcode = '22023', message = 'Department ID is invalid';
  end if;
  if p_department_id::numeric > 9223372036854775807 then
    raise exception using errcode = '22023', message = 'Department ID exceeds PostgreSQL BIGINT range';
  end if;

  target_id := p_department_id::bigint;
  perform 1 from public.departments
  where id = target_id and not deleted
  for update;
  if not found then
    raise exception using errcode = 'P0002', message = 'Department was not found';
  end if;
  if exists (
    select 1 from public.profiles as profile
    where profile.department_id = target_id
  ) then
    raise exception using errcode = '23503', message = 'Department is referenced by profiles';
  end if;

  update public.departments
  set deleted = true
  where id = target_id and not deleted;
  return true;
end;
$$;

create function public.delete_post(p_post_id text)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  target_id bigint;
begin
  if not app_private.is_password_authenticated()
    or not app_private.has_permission('organization.posts.delete') then
    raise exception using errcode = '42501', message = 'Post delete permission is required';
  end if;
  if p_post_id is null or p_post_id !~ '^[1-9][0-9]*$' then
    raise exception using errcode = '22023', message = 'Post ID is invalid';
  end if;
  if p_post_id::numeric > 9223372036854775807 then
    raise exception using errcode = '22023', message = 'Post ID exceeds PostgreSQL BIGINT range';
  end if;

  target_id := p_post_id::bigint;
  perform 1 from public.posts
  where id = target_id and not deleted
  for update;
  if not found then
    raise exception using errcode = 'P0002', message = 'Post was not found';
  end if;
  if exists (
    select 1 from public.profiles as profile
    where profile.post_id = target_id
  ) then
    raise exception using errcode = '23503', message = 'Post is referenced by profiles';
  end if;

  update public.posts
  set deleted = true
  where id = target_id and not deleted;
  return true;
end;
$$;

revoke all on function public.delete_department(text)
  from public, anon, authenticated, service_role;
revoke all on function public.delete_post(text)
  from public, anon, authenticated, service_role;
grant execute on function public.delete_department(text) to authenticated;
grant execute on function public.delete_post(text) to authenticated;

-- Legacy imports are intentionally service-role-only. Both preview and apply
-- validate the full source batch; apply preserves source BIGINT IDs and time.
create function public.import_legacy_departments(p_rows jsonb, p_apply boolean)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  source_count integer;
  distinct_id_count integer;
  already_present_count integer;
  rows_to_insert integer;
  inserted_count integer := 0;
  maximum_department_id bigint;
  imported_department record;
  existing_department public.departments%rowtype;
begin
  if p_apply is null or jsonb_typeof(p_rows) is distinct from 'array' then
    raise exception using errcode = '22023', message = 'Department import input is invalid';
  end if;
  source_count := jsonb_array_length(p_rows);
  if source_count > 100 then
    raise exception using errcode = '22023', message = 'Department import batches cannot exceed 100 rows';
  end if;
  if exists (
    select 1
    from jsonb_to_recordset(p_rows) as source(
      id text, dept_code text, dept_name text, status integer,
      description text, deleted boolean, created_at timestamptz, updated_at timestamptz
    )
    where coalesce(source.id, '') !~ '^[1-9][0-9]*$'
       or source.dept_code is null
       or source.dept_name is null
       or source.status is null
       or source.status not in (0, 1)
       or source.deleted is null
       or source.created_at is null
       or source.updated_at is null
       or source.dept_code <> btrim(source.dept_code)
       or source.dept_name <> btrim(source.dept_name)
       or length(source.dept_code) not between 1 and 64
       or length(source.dept_name) not between 1 and 128
       or coalesce(length(source.description), 0) > 255
  ) then
    raise exception using errcode = '22023', message = 'Department import contains invalid fields';
  end if;
  if exists (
    select 1
    from jsonb_to_recordset(p_rows) as source(id text, dept_code text)
    where source.id::numeric > 9223372036854775807
  ) then
    raise exception using errcode = '22003', message = 'Department ID exceeds PostgreSQL BIGINT range';
  end if;

  select count(distinct source.id)::integer into distinct_id_count
  from jsonb_to_recordset(p_rows) as source(id text);
  if distinct_id_count <> source_count then
    raise exception using errcode = '23505', message = 'Department import contains duplicate IDs';
  end if;
  if exists (
    select lower(btrim(source.dept_code))
    from jsonb_to_recordset(p_rows) as source(dept_code text)
    group by lower(btrim(source.dept_code))
    having count(*) > 1
  ) then
    raise exception using errcode = '23505', message = 'Department import contains duplicate codes';
  end if;

  for imported_department in
    select * from jsonb_to_recordset(p_rows) as source(
      id text, dept_code text, dept_name text, status integer,
      description text, deleted boolean, created_at timestamptz, updated_at timestamptz
    )
  loop
    select * into existing_department
    from public.departments as department
    where department.id = imported_department.id::bigint;
    if found then
      if existing_department.dept_code is distinct from imported_department.dept_code
        or existing_department.dept_name is distinct from imported_department.dept_name
        or existing_department.status is distinct from imported_department.status::smallint
        or existing_department.description is distinct from imported_department.description
        or existing_department.deleted is distinct from imported_department.deleted
        or existing_department.created_at is distinct from imported_department.created_at
        or existing_department.updated_at is distinct from imported_department.updated_at then
        raise exception using errcode = '23505', message = 'Department import conflicts with an existing ID';
      end if;
    end if;
  end loop;

  select count(*)::integer into already_present_count
  from jsonb_to_recordset(p_rows) as source(id text)
  join public.departments as department on department.id = source.id::bigint;
  rows_to_insert := source_count - already_present_count;

  if exists (
    select 1
    from jsonb_to_recordset(p_rows) as source(id text, dept_code text)
    join public.departments as department
      on lower(department.dept_code) = lower(btrim(source.dept_code))
     and department.id <> source.id::bigint
  ) then
    raise exception using errcode = '23505', message = 'Department code conflicts with another ID';
  end if;

  if p_apply then
    if rows_to_insert > 0 then
      insert into public.departments (
        id, dept_code, dept_name, status, description, deleted, created_at, updated_at
      )
      select source.id::bigint, source.dept_code, source.dept_name,
        source.status::smallint, source.description, source.deleted,
        source.created_at, source.updated_at
      from jsonb_to_recordset(p_rows) as source(
        id text, dept_code text, dept_name text, status integer,
        description text, deleted boolean, created_at timestamptz, updated_at timestamptz
      )
      where not exists (
        select 1 from public.departments as existing
        where existing.id = source.id::bigint
      );
      get diagnostics inserted_count = row_count;
    end if;
    select max(id) into maximum_department_id from public.departments;
    if maximum_department_id is not null then
      perform setval(
        pg_get_serial_sequence('public.departments', 'id'),
        maximum_department_id,
        true
      );
    end if;
  end if;

  return jsonb_build_object(
    'sourceCount', source_count,
    'alreadyPresentCount', already_present_count,
    'rowsToInsert', rows_to_insert,
    'insertedCount', inserted_count
  );
end;
$$;

create function public.import_legacy_posts(p_rows jsonb, p_apply boolean)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  source_count integer;
  distinct_id_count integer;
  already_present_count integer;
  rows_to_insert integer;
  inserted_count integer := 0;
  maximum_post_id bigint;
  imported_post record;
  existing_post public.posts%rowtype;
begin
  if p_apply is null or jsonb_typeof(p_rows) is distinct from 'array' then
    raise exception using errcode = '22023', message = 'Post import input is invalid';
  end if;
  source_count := jsonb_array_length(p_rows);
  if source_count > 100 then
    raise exception using errcode = '22023', message = 'Post import batches cannot exceed 100 rows';
  end if;
  if exists (
    select 1
    from jsonb_to_recordset(p_rows) as source(
      id text, post_code text, post_name text, status integer,
      description text, deleted boolean, created_at timestamptz, updated_at timestamptz
    )
    where coalesce(source.id, '') !~ '^[1-9][0-9]*$'
       or source.post_code is null
       or source.post_name is null
       or source.status is null
       or source.status not in (0, 1)
       or source.deleted is null
       or source.created_at is null
       or source.updated_at is null
       or source.post_code <> btrim(source.post_code)
       or source.post_name <> btrim(source.post_name)
       or length(source.post_code) not between 1 and 64
       or length(source.post_name) not between 1 and 128
       or coalesce(length(source.description), 0) > 255
  ) then
    raise exception using errcode = '22023', message = 'Post import contains invalid fields';
  end if;
  if exists (
    select 1
    from jsonb_to_recordset(p_rows) as source(id text, post_code text)
    where source.id::numeric > 9223372036854775807
  ) then
    raise exception using errcode = '22003', message = 'Post ID exceeds PostgreSQL BIGINT range';
  end if;

  select count(distinct source.id)::integer into distinct_id_count
  from jsonb_to_recordset(p_rows) as source(id text);
  if distinct_id_count <> source_count then
    raise exception using errcode = '23505', message = 'Post import contains duplicate IDs';
  end if;
  if exists (
    select lower(btrim(source.post_code))
    from jsonb_to_recordset(p_rows) as source(post_code text)
    group by lower(btrim(source.post_code))
    having count(*) > 1
  ) then
    raise exception using errcode = '23505', message = 'Post import contains duplicate codes';
  end if;

  for imported_post in
    select * from jsonb_to_recordset(p_rows) as source(
      id text, post_code text, post_name text, status integer,
      description text, deleted boolean, created_at timestamptz, updated_at timestamptz
    )
  loop
    select * into existing_post
    from public.posts as post
    where post.id = imported_post.id::bigint;
    if found then
      if existing_post.post_code is distinct from imported_post.post_code
        or existing_post.post_name is distinct from imported_post.post_name
        or existing_post.status is distinct from imported_post.status::smallint
        or existing_post.description is distinct from imported_post.description
        or existing_post.deleted is distinct from imported_post.deleted
        or existing_post.created_at is distinct from imported_post.created_at
        or existing_post.updated_at is distinct from imported_post.updated_at then
        raise exception using errcode = '23505', message = 'Post import conflicts with an existing ID';
      end if;
    end if;
  end loop;

  select count(*)::integer into already_present_count
  from jsonb_to_recordset(p_rows) as source(id text)
  join public.posts as post on post.id = source.id::bigint;
  rows_to_insert := source_count - already_present_count;

  if exists (
    select 1
    from jsonb_to_recordset(p_rows) as source(id text, post_code text)
    join public.posts as post
      on lower(post.post_code) = lower(btrim(source.post_code))
     and post.id <> source.id::bigint
  ) then
    raise exception using errcode = '23505', message = 'Post code conflicts with another ID';
  end if;

  if p_apply then
    if rows_to_insert > 0 then
      insert into public.posts (
        id, post_code, post_name, status, description, deleted, created_at, updated_at
      )
      select source.id::bigint, source.post_code, source.post_name,
        source.status::smallint, source.description, source.deleted,
        source.created_at, source.updated_at
      from jsonb_to_recordset(p_rows) as source(
        id text, post_code text, post_name text, status integer,
        description text, deleted boolean, created_at timestamptz, updated_at timestamptz
      )
      where not exists (
        select 1 from public.posts as existing
        where existing.id = source.id::bigint
      );
      get diagnostics inserted_count = row_count;
    end if;
    select max(id) into maximum_post_id from public.posts;
    if maximum_post_id is not null then
      perform setval(
        pg_get_serial_sequence('public.posts', 'id'),
        maximum_post_id,
        true
      );
    end if;
  end if;

  return jsonb_build_object(
    'sourceCount', source_count,
    'alreadyPresentCount', already_present_count,
    'rowsToInsert', rows_to_insert,
    'insertedCount', inserted_count
  );
end;
$$;

revoke all on function public.import_legacy_departments(jsonb, boolean)
  from public, anon, authenticated;
revoke all on function public.import_legacy_posts(jsonb, boolean)
  from public, anon, authenticated;
grant execute on function public.import_legacy_departments(jsonb, boolean) to service_role;
grant execute on function public.import_legacy_posts(jsonb, boolean) to service_role;

-- Preflight profile backfills without returning BIGINT values through the
-- browser-facing Data API. Deleted directory rows still count as valid legacy
-- references because profiles retain their original department/post IDs.
create function public.assert_legacy_organization_references(
  p_department_ids text[],
  p_post_ids text[]
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  organization_id text;
begin
  if cardinality(coalesce(p_department_ids, array[]::text[])) > 100
    or cardinality(coalesce(p_post_ids, array[]::text[])) > 100 then
    raise exception using errcode = '22023', message = 'Organization reference batches cannot exceed 100 IDs';
  end if;

  foreach organization_id in array coalesce(p_department_ids, array[]::text[]) loop
    if organization_id is null or organization_id !~ '^[1-9][0-9]*$' then
      raise exception using errcode = '22023', message = 'Department reference ID is invalid';
    end if;
    if organization_id::numeric > 9223372036854775807 then
      raise exception using errcode = '22003', message = 'Department reference ID exceeds PostgreSQL BIGINT range';
    end if;
    perform 1 from public.departments as department
    where department.id = organization_id::bigint;
    if not found then
      raise exception using errcode = '23503', message = 'A legacy profile references a missing department';
    end if;
  end loop;

  foreach organization_id in array coalesce(p_post_ids, array[]::text[]) loop
    if organization_id is null or organization_id !~ '^[1-9][0-9]*$' then
      raise exception using errcode = '22023', message = 'Post reference ID is invalid';
    end if;
    if organization_id::numeric > 9223372036854775807 then
      raise exception using errcode = '22003', message = 'Post reference ID exceeds PostgreSQL BIGINT range';
    end if;
    perform 1 from public.posts as post
    where post.id = organization_id::bigint;
    if not found then
      raise exception using errcode = '23503', message = 'A legacy profile references a missing post';
    end if;
  end loop;
end;
$$;

revoke all on function public.assert_legacy_organization_references(text[], text[])
  from public, anon, authenticated;
grant execute on function public.assert_legacy_organization_references(text[], text[])
  to service_role;
