-- Supabase Auth identities map to stable BIGINT business profile IDs.
-- auth_user_id stays nullable during legacy account preflight/import and must
-- become NOT NULL in a later migration after every eligible account is mapped.
create table public.profiles (
  id bigint generated by default as identity primary key,
  auth_user_id uuid unique references auth.users (id),
  login_name text not null check (length(trim(login_name)) between 1 and 64),
  display_name text not null check (length(trim(display_name)) between 1 and 128),
  email text not null check (length(trim(email)) between 3 and 320),
  phone text,
  avatar_url text,
  is_active boolean not null default true,
  must_reset_password boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index profiles_login_name_lower_uidx on public.profiles (lower(login_name));
create unique index profiles_email_lower_uidx on public.profiles (lower(email));

comment on table public.profiles is
  'Business identity. id remains BIGINT; auth_user_id maps to Supabase Auth UUID.';
comment on column public.profiles.auth_user_id is
  'Nullable only during staged legacy import; set NOT NULL after account preflight and mapping.';

create table public.roles (
  id bigint generated by default as identity primary key,
  code text not null unique check (code ~ '^[A-Z][A-Z0-9_]{1,63}$'),
  name text not null check (length(trim(name)) between 1 and 128),
  description text,
  is_system boolean not null default false,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.permission_catalog (
  permission_key text primary key check (
    permission_key ~ '^[a-z][a-z0-9_-]*\.[a-z][a-z0-9_-]*\.[a-z][a-z0-9_-]*$'
  ),
  description text not null,
  created_at timestamptz not null default now()
);

create table public.user_roles (
  user_id bigint not null references public.profiles (id) on delete cascade,
  role_id bigint not null references public.roles (id),
  created_at timestamptz not null default now(),
  primary key (user_id, role_id)
);

create table public.role_permissions (
  role_id bigint not null references public.roles (id),
  permission_key text not null references public.permission_catalog (permission_key),
  created_at timestamptz not null default now(),
  primary key (role_id, permission_key)
);

create index user_roles_role_id_idx on public.user_roles (role_id, user_id);
create index role_permissions_permission_key_idx on public.role_permissions (permission_key, role_id);

create schema app_private;
revoke all on schema app_private from public, anon, authenticated;
grant usage on schema app_private to authenticated;

create function app_private.is_current_profile(p_profile_id bigint)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.profiles as profile
    where profile.id = p_profile_id
      and profile.auth_user_id = (select auth.uid())
      and profile.is_active
  );
$$;

create function app_private.can_read_role(p_role_id bigint)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.user_roles as user_role
    join public.profiles as profile on profile.id = user_role.user_id
    join public.roles as role on role.id = user_role.role_id
    where user_role.role_id = p_role_id
      and profile.auth_user_id = (select auth.uid())
      and profile.is_active
      and role.is_active
  );
$$;

create function app_private.has_permission(p_permission_key text)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.profiles as profile
    join public.user_roles as user_role on user_role.user_id = profile.id
    join public.roles as role on role.id = user_role.role_id
    where profile.auth_user_id = (select auth.uid())
      and profile.is_active
      and role.is_active
      and (
        role.code = 'SUPER_ADMIN'
        or exists (
          select 1
          from public.role_permissions as role_permission
          where role_permission.role_id = role.id
            and role_permission.permission_key = p_permission_key
        )
      )
  );
$$;

create function app_private.touch_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

revoke all on function app_private.is_current_profile(bigint) from public, anon;
revoke all on function app_private.can_read_role(bigint) from public, anon;
revoke all on function app_private.has_permission(text) from public, anon;
revoke all on function app_private.touch_updated_at() from public, anon, authenticated;
grant execute on function app_private.is_current_profile(bigint) to authenticated;
grant execute on function app_private.can_read_role(bigint) to authenticated;
grant execute on function app_private.has_permission(text) to authenticated;
grant execute on function app_private.touch_updated_at() to authenticated;

create trigger profiles_touch_updated_at
before update on public.profiles
for each row execute function app_private.touch_updated_at();

create trigger roles_touch_updated_at
before update on public.roles
for each row execute function app_private.touch_updated_at();

alter table public.profiles enable row level security;
alter table public.roles enable row level security;
alter table public.permission_catalog enable row level security;
alter table public.user_roles enable row level security;
alter table public.role_permissions enable row level security;

create policy profiles_read_self_or_user_reader
on public.profiles for select to authenticated
using (
  (select app_private.is_current_profile(id))
  or (select app_private.has_permission('administration.users.read'))
);

create policy profiles_update_self_or_user_editor
on public.profiles for update to authenticated
using (
  (select app_private.is_current_profile(id))
  or (select app_private.has_permission('administration.users.update'))
)
with check (
  (select app_private.is_current_profile(id))
  or (select app_private.has_permission('administration.users.update'))
);

create policy roles_read_assigned_or_role_reader
on public.roles for select to authenticated
using (
  (select app_private.can_read_role(id))
  or (select app_private.has_permission('administration.roles.read'))
);

create policy roles_create
on public.roles for insert to authenticated
with check ((select app_private.has_permission('administration.roles.create')));

create policy roles_update
on public.roles for update to authenticated
using ((select app_private.has_permission('administration.roles.update')))
with check ((select app_private.has_permission('administration.roles.update')));

create policy roles_delete
on public.roles for delete to authenticated
using ((select app_private.has_permission('administration.roles.delete')));

create policy permission_catalog_read_authenticated
on public.permission_catalog for select to authenticated
using (true);

create policy user_roles_read_self_or_administrator
on public.user_roles for select to authenticated
using (
  (select app_private.is_current_profile(user_id))
  or (select app_private.has_permission('administration.users.read'))
  or (select app_private.has_permission('administration.roles.read'))
);

create policy user_roles_assign
on public.user_roles for insert to authenticated
with check ((select app_private.has_permission('administration.users.assign_roles')));

create policy user_roles_unassign
on public.user_roles for delete to authenticated
using ((select app_private.has_permission('administration.users.assign_roles')));

create policy role_permissions_read_assigned_or_role_reader
on public.role_permissions for select to authenticated
using (
  (select app_private.can_read_role(role_id))
  or (select app_private.has_permission('administration.roles.read'))
);

create policy role_permissions_assign
on public.role_permissions for insert to authenticated
with check ((select app_private.has_permission('administration.roles.assign_permissions')));

create policy role_permissions_unassign
on public.role_permissions for delete to authenticated
using ((select app_private.has_permission('administration.roles.assign_permissions')));

revoke all on public.profiles, public.roles, public.permission_catalog,
  public.user_roles, public.role_permissions from anon, authenticated;
grant select on public.profiles, public.roles, public.permission_catalog,
  public.user_roles, public.role_permissions to authenticated;
grant update (display_name, phone, avatar_url) on public.profiles to authenticated;
grant insert (code, name, description), update (name, description, is_active), delete
  on public.roles to authenticated;
grant insert, delete on public.user_roles to authenticated;
grant insert, delete on public.role_permissions to authenticated;
grant usage, select on all sequences in schema public to authenticated;
