-- Dictionary and system configuration tables retain legacy behavior while
-- keeping BIGINT values text-only at the browser RPC boundary.

-- MySQL's utf8mb4_unicode_ci was case-insensitive for these business keys.
-- ICU primary-strength comparison ignores both case and accents, closely
-- matching that legacy uniqueness contract.
create collation if not exists app_private.legacy_utf8mb4_unicode_ci (
  provider = icu,
  locale = 'und-u-ks-level1',
  deterministic = false
);

insert into public.permission_catalog (permission_key, description)
values
  ('configuration.dictionaries.read', '读取数据字典'),
  ('configuration.dictionaries.create', '创建数据字典'),
  ('configuration.dictionaries.update', '更新数据字典'),
  ('configuration.dictionaries.delete', '删除数据字典'),
  ('configuration.system.read', '读取系统配置'),
  ('configuration.system.update', '更新系统配置')
on conflict (permission_key) do update
set description = excluded.description;

create table public.dict_types (
  id bigint generated by default as identity primary key,
  dict_code varchar(64) not null,
  dict_name varchar(128) not null check (length(trim(dict_name)) between 1 and 128),
  status smallint not null default 1 check (status in (0, 1)),
  description varchar(255),
  created_by bigint references public.profiles (id) on delete set null,
  created_at timestamptz not null default now(),
  updated_by bigint references public.profiles (id) on delete set null,
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  constraint dict_types_code_not_blank check (length(trim(dict_code)) between 1 and 64)
);

create table public.dict_items (
  id bigint generated by default as identity primary key,
  dict_type_id bigint not null references public.dict_types (id) on delete restrict,
  item_value varchar(64) not null check (length(trim(item_value)) between 1 and 64),
  item_label varchar(128) not null check (length(trim(item_label)) between 1 and 128),
  sort_order integer not null default 0,
  status smallint not null default 1 check (status in (0, 1)),
  description varchar(255),
  created_by bigint references public.profiles (id) on delete set null,
  created_at timestamptz not null default now(),
  updated_by bigint references public.profiles (id) on delete set null,
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

create table public.system_configs (
  id bigint generated by default as identity primary key,
  config_code varchar(64) not null,
  config_name varchar(128) not null check (length(trim(config_name)) between 1 and 128),
  config_value text not null,
  value_type varchar(32) not null default 'STRING'
    check (value_type in ('STRING', 'NUMBER', 'BOOLEAN', 'JSON')),
  status smallint not null default 1 check (status in (0, 1)),
  description varchar(255),
  created_by bigint references public.profiles (id) on delete set null,
  created_at timestamptz not null default now(),
  updated_by bigint references public.profiles (id) on delete set null,
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  constraint system_configs_code_not_blank check (length(trim(config_code)) between 1 and 64)
);

create unique index dict_types_code_legacy_ci_uidx
  on public.dict_types (dict_code collate app_private.legacy_utf8mb4_unicode_ci);
create unique index system_configs_code_legacy_ci_uidx
  on public.system_configs (config_code collate app_private.legacy_utf8mb4_unicode_ci);
create unique index dict_items_active_type_value_uidx
  on public.dict_items (dict_type_id, (item_value collate app_private.legacy_utf8mb4_unicode_ci))
  where deleted_at is null;
create index dict_items_type_status_sort_idx
  on public.dict_items (dict_type_id, status, sort_order, id)
  where deleted_at is null;
create index dict_types_status_deleted_idx
  on public.dict_types (status, deleted_at, id);
create index system_configs_status_deleted_idx
  on public.system_configs (status, deleted_at, id);

comment on table public.dict_types is
  'Legacy data dictionary types; status 0/1 and soft deletion preserve the Fastify module behavior.';
comment on table public.dict_items is
  'Legacy dictionary values with per-type uniqueness, sortable order, status and soft deletion.';
comment on table public.system_configs is
  'Legacy application settings only. Deployment credentials and Supabase keys belong in local/server secret configuration, not this table.';

create trigger dict_types_touch_updated_at
before update on public.dict_types
for each row execute function app_private.touch_updated_at();
create trigger dict_items_touch_updated_at
before update on public.dict_items
for each row execute function app_private.touch_updated_at();
create trigger system_configs_touch_updated_at
before update on public.system_configs
for each row execute function app_private.touch_updated_at();

alter table public.dict_types enable row level security;
alter table public.dict_items enable row level security;
alter table public.system_configs enable row level security;

-- Direct table access stays closed. Permission-checked RPCs expose only
-- decimal-text BIGINT identifiers; RLS policies also protect any future grants.
revoke all on public.dict_types, public.dict_items, public.system_configs
  from public, anon, authenticated, service_role;

revoke all on sequence public.dict_types_id_seq,
  public.dict_items_id_seq,
  public.system_configs_id_seq
  from public, anon, authenticated, service_role;

create policy dict_types_read_authorized
on public.dict_types for select to authenticated
using (
  (select app_private.is_password_authenticated())
  and (select app_private.has_permission('configuration.dictionaries.read'))
);
create policy dict_types_create_authorized
on public.dict_types for insert to authenticated
with check (
  (select app_private.is_password_authenticated())
  and (select app_private.has_permission('configuration.dictionaries.create'))
);
create policy dict_types_update_authorized
on public.dict_types for update to authenticated
using (
  (select app_private.is_password_authenticated())
  and (select app_private.has_permission('configuration.dictionaries.update'))
)
with check (
  (select app_private.is_password_authenticated())
  and (select app_private.has_permission('configuration.dictionaries.update'))
);

create policy dict_items_read_authorized
on public.dict_items for select to authenticated
using (
  (select app_private.is_password_authenticated())
  and (select app_private.has_permission('configuration.dictionaries.read'))
);
create policy dict_items_create_authorized
on public.dict_items for insert to authenticated
with check (
  (select app_private.is_password_authenticated())
  and (select app_private.has_permission('configuration.dictionaries.create'))
);
create policy dict_items_update_authorized
on public.dict_items for update to authenticated
using (
  (select app_private.is_password_authenticated())
  and (select app_private.has_permission('configuration.dictionaries.update'))
)
with check (
  (select app_private.is_password_authenticated())
  and (select app_private.has_permission('configuration.dictionaries.update'))
);

create policy system_configs_read_authorized
on public.system_configs for select to authenticated
using (
  (select app_private.is_password_authenticated())
  and (select app_private.has_permission('configuration.system.read'))
);
create policy system_configs_create_authorized
on public.system_configs for insert to authenticated
with check (
  (select app_private.is_password_authenticated())
  and (select app_private.has_permission('configuration.system.update'))
);
create policy system_configs_update_authorized
on public.system_configs for update to authenticated
using (
  (select app_private.is_password_authenticated())
  and (select app_private.has_permission('configuration.system.update'))
)
with check (
  (select app_private.is_password_authenticated())
  and (select app_private.has_permission('configuration.system.update'))
);

create function app_private.dictionary_type_read_model(p_id bigint)
returns jsonb
language sql
stable
security definer
set search_path = ''
as $$
  select jsonb_build_object(
    'id', dictionary_type.id::text,
    'dictCode', dictionary_type.dict_code,
    'dictName', dictionary_type.dict_name,
    'status', dictionary_type.status,
    'description', dictionary_type.description,
    'createdAt', dictionary_type.created_at,
    'updatedAt', dictionary_type.updated_at
  )
  from public.dict_types as dictionary_type
  where dictionary_type.id = p_id
    and dictionary_type.deleted_at is null;
$$;

create function app_private.dictionary_item_read_model(p_id bigint)
returns jsonb
language sql
stable
security definer
set search_path = ''
as $$
  select jsonb_build_object(
    'id', dictionary_item.id::text,
    'dictTypeId', dictionary_item.dict_type_id::text,
    'itemValue', dictionary_item.item_value,
    'itemLabel', dictionary_item.item_label,
    'sortOrder', dictionary_item.sort_order,
    'status', dictionary_item.status,
    'description', dictionary_item.description,
    'createdAt', dictionary_item.created_at,
    'updatedAt', dictionary_item.updated_at
  )
  from public.dict_items as dictionary_item
  where dictionary_item.id = p_id
    and dictionary_item.deleted_at is null;
$$;

create function app_private.system_config_read_model(p_id bigint)
returns jsonb
language sql
stable
security definer
set search_path = ''
as $$
  select jsonb_build_object(
    'id', config.id::text,
    'configCode', config.config_code,
    'configName', config.config_name,
    'configValue', config.config_value,
    'valueType', config.value_type,
    'status', config.status,
    'description', config.description,
    'createdAt', config.created_at,
    'updatedAt', config.updated_at
  )
  from public.system_configs as config
  where config.id = p_id
    and config.deleted_at is null;
$$;

create or replace function app_private.require_configuration_permission(p_permission_key text)
returns void
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
  if (select auth.uid()) is null or not (select app_private.is_password_authenticated()) then
    raise exception using errcode = '42501', message = 'A registered password-authenticated session is required';
  end if;
  if not (select app_private.has_permission(p_permission_key)) then
    raise exception using errcode = '42501', message = 'Configuration permission is required';
  end if;
end;
$$;

revoke all on function app_private.dictionary_type_read_model(bigint),
  app_private.dictionary_item_read_model(bigint),
  app_private.system_config_read_model(bigint),
  app_private.require_configuration_permission(text)
  from public, anon, authenticated, service_role;

create function public.admin_dictionary_types(
  p_dict_code text,
  p_dict_name text,
  p_status smallint,
  p_page integer,
  p_page_size integer
)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
  perform app_private.require_configuration_permission('configuration.dictionaries.read');
  if p_page is null or p_page < 1 or p_page_size is null or p_page_size not between 1 and 100
    or (p_status is not null and p_status not in (0, 1)) then
    raise exception using errcode = '22023', message = 'Dictionary filters are invalid';
  end if;

  return (
    with filtered as materialized (
      select dictionary_type.id
      from public.dict_types as dictionary_type
      where dictionary_type.deleted_at is null
        and (p_dict_code is null or dictionary_type.dict_code ilike '%' || trim(p_dict_code) || '%')
        and (p_dict_name is null or dictionary_type.dict_name ilike '%' || trim(p_dict_name) || '%')
        and (p_status is null or dictionary_type.status = p_status)
    ),
    page_rows as (
      select filtered.id
      from filtered
      order by filtered.id desc
      limit p_page_size
      offset ((p_page::bigint - 1) * p_page_size::bigint)
    )
    select jsonb_build_object(
      'items', coalesce(
        (
          select jsonb_agg(app_private.dictionary_type_read_model(page_rows.id) order by page_rows.id desc)
          from page_rows
        ),
        '[]'::jsonb
      ),
      'total', (select count(*)::integer from filtered),
      'page', p_page,
      'pageSize', p_page_size
    )
  );
end;
$$;

create function public.admin_dictionary_items(p_dict_type_id text)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  target_type_id bigint;
begin
  perform app_private.require_configuration_permission('configuration.dictionaries.read');
  if coalesce(p_dict_type_id, '') !~ '^[1-9][0-9]*$' then
    raise exception using errcode = '22023', message = 'Dictionary type ID is invalid';
  end if;
  if p_dict_type_id::numeric > 9223372036854775807 then
    raise exception using errcode = '22023', message = 'Dictionary type ID is invalid';
  end if;
  target_type_id := p_dict_type_id::bigint;
  if not exists (
    select 1 from public.dict_types as dictionary_type
    where dictionary_type.id = target_type_id and dictionary_type.deleted_at is null
  ) then
    raise exception using errcode = 'P0002', message = 'Dictionary type was not found';
  end if;

  return coalesce(
    (
      select jsonb_agg(
        app_private.dictionary_item_read_model(dictionary_item.id)
        order by dictionary_item.sort_order, dictionary_item.id
      )
      from public.dict_items as dictionary_item
      where dictionary_item.dict_type_id = target_type_id
        and dictionary_item.deleted_at is null
    ),
    '[]'::jsonb
  );
end;
$$;

create function public.dictionary_options(p_dict_code text, p_enabled_only boolean)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
  perform app_private.require_configuration_permission('configuration.dictionaries.read');
  if nullif(trim(p_dict_code), '') is null or p_enabled_only is null then
    raise exception using errcode = '22023', message = 'Dictionary option query is invalid';
  end if;

  return coalesce(
    (
      select jsonb_agg(
        jsonb_build_object(
          'id', dictionary_item.id::text,
          'label', dictionary_item.item_label,
          'value', dictionary_item.item_value,
          'status', dictionary_item.status
        ) order by dictionary_item.sort_order, dictionary_item.id
      )
      from public.dict_types as dictionary_type
      join public.dict_items as dictionary_item
        on dictionary_item.dict_type_id = dictionary_type.id
      where dictionary_type.dict_code collate app_private.legacy_utf8mb4_unicode_ci
          = trim(p_dict_code) collate app_private.legacy_utf8mb4_unicode_ci
        and dictionary_type.deleted_at is null
        and dictionary_item.deleted_at is null
        and (
          not p_enabled_only
          or (dictionary_type.status = 1 and dictionary_item.status = 1)
        )
    ),
    '[]'::jsonb
  );
end;
$$;

create function public.save_dictionary_type(
  p_id text,
  p_dict_code text,
  p_dict_name text,
  p_status smallint,
  p_description text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  target_id bigint;
  actor_id bigint;
begin
  if nullif(trim(p_dict_code), '') is null or length(trim(p_dict_code)) > 64
    or nullif(trim(p_dict_name), '') is null or length(trim(p_dict_name)) > 128
    or coalesce(length(trim(p_description)), 0) > 255
    or p_status is null or p_status not in (0, 1) then
    raise exception using errcode = '22023', message = 'Dictionary type fields are invalid';
  end if;
  if p_id is null then
    perform app_private.require_configuration_permission('configuration.dictionaries.create');
  else
    perform app_private.require_configuration_permission('configuration.dictionaries.update');
    if p_id !~ '^[1-9][0-9]*$' then
      raise exception using errcode = '22023', message = 'Dictionary type ID is invalid';
    end if;
    if p_id::numeric > 9223372036854775807 then
      raise exception using errcode = '22023', message = 'Dictionary type ID is invalid';
    end if;
    target_id := p_id::bigint;
    perform dictionary_type.id
    from public.dict_types as dictionary_type
    where dictionary_type.id = target_id and dictionary_type.deleted_at is null
    for update;
    if not found then
      raise exception using errcode = 'P0002', message = 'Dictionary type was not found';
    end if;
  end if;
  select profile.id into actor_id
  from public.profiles as profile
  where profile.auth_user_id = (select auth.uid())
    and profile.is_active
    and profile.deleted_at is null;

  if p_id is null then
    insert into public.dict_types (dict_code, dict_name, status, description, created_by, updated_by)
    values (trim(p_dict_code), trim(p_dict_name), p_status, nullif(trim(p_description), ''), actor_id, actor_id)
    returning id into target_id;
  else
    update public.dict_types as dictionary_type
    set dict_code = trim(p_dict_code),
        dict_name = trim(p_dict_name),
        status = p_status,
        description = nullif(trim(p_description), ''),
        updated_by = actor_id
    where dictionary_type.id = target_id and dictionary_type.deleted_at is null;
  end if;
  return app_private.dictionary_type_read_model(target_id);
end;
$$;

create function public.save_dictionary_item(
  p_id text,
  p_dict_type_id text,
  p_item_value text,
  p_item_label text,
  p_sort_order integer,
  p_status smallint,
  p_description text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  target_id bigint;
  target_type_id bigint;
  existing_type_id bigint;
  actor_id bigint;
begin
  if coalesce(p_dict_type_id, '') !~ '^[1-9][0-9]*$'
    or nullif(trim(p_item_value), '') is null or length(trim(p_item_value)) > 64
    or nullif(trim(p_item_label), '') is null or length(trim(p_item_label)) > 128
    or p_sort_order is null or p_sort_order < -2147483648
    or p_status is null or p_status not in (0, 1)
    or coalesce(length(trim(p_description)), 0) > 255 then
    raise exception using errcode = '22023', message = 'Dictionary item fields are invalid';
  end if;
  if p_dict_type_id::numeric > 9223372036854775807 then
    raise exception using errcode = '22023', message = 'Dictionary type ID is invalid';
  end if;
  target_type_id := p_dict_type_id::bigint;
  perform dictionary_type.id
  from public.dict_types as dictionary_type
  where dictionary_type.id = target_type_id and dictionary_type.deleted_at is null
  for update;
  if not found then
    raise exception using errcode = 'P0002', message = 'Dictionary type was not found';
  end if;

  if p_id is null then
    perform app_private.require_configuration_permission('configuration.dictionaries.create');
  else
    perform app_private.require_configuration_permission('configuration.dictionaries.update');
    if p_id !~ '^[1-9][0-9]*$' then
      raise exception using errcode = '22023', message = 'Dictionary item ID is invalid';
    end if;
    if p_id::numeric > 9223372036854775807 then
      raise exception using errcode = '22023', message = 'Dictionary item ID is invalid';
    end if;
    target_id := p_id::bigint;
    select dictionary_item.dict_type_id into existing_type_id
    from public.dict_items as dictionary_item
    where dictionary_item.id = target_id and dictionary_item.deleted_at is null
    for update;
    if not found then
      raise exception using errcode = 'P0002', message = 'Dictionary item was not found';
    end if;
    if existing_type_id <> target_type_id then
      raise exception using errcode = '23514', message = 'Dictionary item cannot move between types';
    end if;
  end if;

  select profile.id into actor_id
  from public.profiles as profile
  where profile.auth_user_id = (select auth.uid())
    and profile.is_active
    and profile.deleted_at is null;

  if p_id is null then
    insert into public.dict_items (
      dict_type_id, item_value, item_label, sort_order, status, description, created_by, updated_by
    ) values (
      target_type_id, trim(p_item_value), trim(p_item_label), p_sort_order, p_status,
      nullif(trim(p_description), ''), actor_id, actor_id
    ) returning id into target_id;
  else
    update public.dict_items as dictionary_item
    set item_value = trim(p_item_value),
        item_label = trim(p_item_label),
        sort_order = p_sort_order,
        status = p_status,
        description = nullif(trim(p_description), ''),
        updated_by = actor_id
    where dictionary_item.id = target_id
      and dictionary_item.dict_type_id = target_type_id
      and dictionary_item.deleted_at is null;
  end if;
  return app_private.dictionary_item_read_model(target_id);
end;
$$;

create function public.replace_dictionary_item_order(p_dict_type_id text, p_items jsonb)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  target_type_id bigint;
  actor_id bigint;
  requested_count integer;
begin
  perform app_private.require_configuration_permission('configuration.dictionaries.update');
  if coalesce(p_dict_type_id, '') !~ '^[1-9][0-9]*$'
    or jsonb_typeof(p_items) is distinct from 'array' then
    raise exception using errcode = '22023', message = 'Dictionary item order input is invalid';
  end if;
  if p_dict_type_id::numeric > 9223372036854775807
    or jsonb_array_length(p_items) > 500 then
    raise exception using errcode = '22023', message = 'Dictionary item order input is invalid';
  end if;
  target_type_id := p_dict_type_id::bigint;
  perform dictionary_type.id
  from public.dict_types as dictionary_type
  where dictionary_type.id = target_type_id and dictionary_type.deleted_at is null
  for update;
  if not found then
    raise exception using errcode = 'P0002', message = 'Dictionary type was not found';
  end if;
  if exists (
    select 1
    from jsonb_to_recordset(p_items) as requested(id text, "sortOrder" integer)
    where coalesce(requested.id, '') !~ '^[1-9][0-9]*$'
      or case
        when requested.id ~ '^[1-9][0-9]*$'
          then requested.id::numeric > 9223372036854775807
        else false
      end
      or requested."sortOrder" is null or requested."sortOrder" < 0
  ) or (
    select count(distinct requested.id)::integer
    from jsonb_to_recordset(p_items) as requested(id text, "sortOrder" integer)
  ) <> jsonb_array_length(p_items) then
    raise exception using errcode = '22023', message = 'Dictionary item order rows are invalid or duplicated';
  end if;

  select count(*)::integer into requested_count
  from jsonb_to_recordset(p_items) as requested(id text, "sortOrder" integer);
  if requested_count <> (
    select count(*)::integer from public.dict_items as dictionary_item
    where dictionary_item.dict_type_id = target_type_id and dictionary_item.deleted_at is null
  ) or exists (
    select 1
    from jsonb_to_recordset(p_items) as requested(id text, "sortOrder" integer)
    left join public.dict_items as dictionary_item
      on dictionary_item.id = requested.id::bigint
     and dictionary_item.dict_type_id = target_type_id
     and dictionary_item.deleted_at is null
    where dictionary_item.id is null
  ) then
    raise exception using errcode = '23514', message = 'Order replacement must include every active dictionary item of this type';
  end if;

  select profile.id into actor_id
  from public.profiles as profile
  where profile.auth_user_id = (select auth.uid())
    and profile.is_active
    and profile.deleted_at is null;
  update public.dict_items as dictionary_item
  set sort_order = requested."sortOrder",
      updated_by = actor_id
  from jsonb_to_recordset(p_items) as requested(id text, "sortOrder" integer)
  where dictionary_item.id = requested.id::bigint
    and dictionary_item.dict_type_id = target_type_id
    and dictionary_item.deleted_at is null;
end;
$$;

create function public.soft_delete_dictionary_type(p_dict_type_id text)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  target_type_id bigint;
  actor_id bigint;
begin
  perform app_private.require_configuration_permission('configuration.dictionaries.delete');
  if coalesce(p_dict_type_id, '') !~ '^[1-9][0-9]*$' then
    raise exception using errcode = '22023', message = 'Dictionary type ID is invalid';
  end if;
  if p_dict_type_id::numeric > 9223372036854775807 then
    raise exception using errcode = '22023', message = 'Dictionary type ID is invalid';
  end if;
  target_type_id := p_dict_type_id::bigint;
  perform dictionary_type.id
  from public.dict_types as dictionary_type
  where dictionary_type.id = target_type_id and dictionary_type.deleted_at is null
  for update;
  if not found then
    raise exception using errcode = 'P0002', message = 'Dictionary type was not found';
  end if;
  if exists (
    select 1 from public.dict_items as dictionary_item
    where dictionary_item.dict_type_id = target_type_id
      and dictionary_item.status = 1
      and dictionary_item.deleted_at is null
  ) then
    raise exception using errcode = '23503', message = 'Dictionary type contains active items';
  end if;
  select profile.id into actor_id
  from public.profiles as profile
  where profile.auth_user_id = (select auth.uid())
    and profile.is_active
    and profile.deleted_at is null;
  update public.dict_types as dictionary_type
  set deleted_at = now(), updated_by = actor_id
  where dictionary_type.id = target_type_id and dictionary_type.deleted_at is null;
  if not found then
    raise exception using errcode = 'P0002', message = 'Dictionary type was not found';
  end if;
end;
$$;

create function public.soft_delete_dictionary_item(p_dict_item_id text)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  target_item_id bigint;
  actor_id bigint;
begin
  perform app_private.require_configuration_permission('configuration.dictionaries.delete');
  if coalesce(p_dict_item_id, '') !~ '^[1-9][0-9]*$' then
    raise exception using errcode = '22023', message = 'Dictionary item ID is invalid';
  end if;
  if p_dict_item_id::numeric > 9223372036854775807 then
    raise exception using errcode = '22023', message = 'Dictionary item ID is invalid';
  end if;
  target_item_id := p_dict_item_id::bigint;
  select profile.id into actor_id
  from public.profiles as profile
  where profile.auth_user_id = (select auth.uid())
    and profile.is_active
    and profile.deleted_at is null;
  update public.dict_items as dictionary_item
  set deleted_at = now(), updated_by = actor_id
  where dictionary_item.id = target_item_id and dictionary_item.deleted_at is null;
  if not found then
    raise exception using errcode = 'P0002', message = 'Dictionary item was not found';
  end if;
end;
$$;

create function public.admin_system_configurations(
  p_config_code text,
  p_config_name text,
  p_status smallint,
  p_page integer,
  p_page_size integer
)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
  perform app_private.require_configuration_permission('configuration.system.read');
  if p_page is null or p_page < 1 or p_page_size is null or p_page_size not between 1 and 100
    or (p_status is not null and p_status not in (0, 1)) then
    raise exception using errcode = '22023', message = 'Configuration filters are invalid';
  end if;

  return (
    with filtered as materialized (
      select config.id
      from public.system_configs as config
      where config.deleted_at is null
        and (p_config_code is null or config.config_code ilike '%' || trim(p_config_code) || '%')
        and (p_config_name is null or config.config_name ilike '%' || trim(p_config_name) || '%')
        and (p_status is null or config.status = p_status)
    ),
    page_rows as (
      select filtered.id
      from filtered
      order by filtered.id desc
      limit p_page_size
      offset ((p_page::bigint - 1) * p_page_size::bigint)
    )
    select jsonb_build_object(
      'items', coalesce(
        (
          select jsonb_agg(app_private.system_config_read_model(page_rows.id) order by page_rows.id desc)
          from page_rows
        ),
        '[]'::jsonb
      ),
      'total', (select count(*)::integer from filtered),
      'page', p_page,
      'pageSize', p_page_size
    )
  );
end;
$$;

create function public.system_configuration_value(p_config_code text)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  result jsonb;
begin
  perform app_private.require_configuration_permission('configuration.system.read');
  select jsonb_build_object(
    'configCode', config.config_code,
    'configValue', config.config_value,
    'valueType', config.value_type
  ) into result
  from public.system_configs as config
  where config.config_code collate app_private.legacy_utf8mb4_unicode_ci
      = trim(p_config_code) collate app_private.legacy_utf8mb4_unicode_ci
    and config.status = 1
    and config.deleted_at is null;
  if result is null then
    raise exception using errcode = 'P0002', message = 'Configuration was not found or is disabled';
  end if;
  return result;
end;
$$;

create function public.save_system_configuration(
  p_id text,
  p_config_code text,
  p_config_name text,
  p_config_value text,
  p_value_type text,
  p_status smallint,
  p_description text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  target_id bigint;
  normalized_value_type text;
  actor_id bigint;
begin
  perform app_private.require_configuration_permission('configuration.system.update');
  if nullif(trim(p_config_code), '') is null or length(trim(p_config_code)) > 64
    or nullif(trim(p_config_name), '') is null or length(trim(p_config_name)) > 128
    or nullif(trim(p_config_value), '') is null
    or coalesce(length(trim(p_description)), 0) > 255
    or p_status is null or p_status not in (0, 1) then
    raise exception using errcode = '22023', message = 'Configuration fields are invalid';
  end if;
  normalized_value_type := upper(trim(coalesce(p_value_type, 'STRING')));
  if normalized_value_type not in ('STRING', 'NUMBER', 'BOOLEAN', 'JSON') then
    normalized_value_type := 'STRING';
  end if;

  if p_id is not null then
    if p_id !~ '^[1-9][0-9]*$' then
      raise exception using errcode = '22023', message = 'Configuration ID is invalid';
    end if;
    if p_id::numeric > 9223372036854775807 then
      raise exception using errcode = '22023', message = 'Configuration ID is invalid';
    end if;
    target_id := p_id::bigint;
    perform config.id
    from public.system_configs as config
    where config.id = target_id and config.deleted_at is null
    for update;
    if not found then
      raise exception using errcode = 'P0002', message = 'Configuration was not found';
    end if;
  end if;
  select profile.id into actor_id
  from public.profiles as profile
  where profile.auth_user_id = (select auth.uid())
    and profile.is_active
    and profile.deleted_at is null;

  if p_id is null then
    insert into public.system_configs (
      config_code, config_name, config_value, value_type, status, description, created_by, updated_by
    ) values (
      trim(p_config_code), trim(p_config_name), trim(p_config_value), normalized_value_type,
      p_status, nullif(trim(p_description), ''), actor_id, actor_id
    ) returning id into target_id;
  else
    update public.system_configs as config
    set config_code = trim(p_config_code),
        config_name = trim(p_config_name),
        config_value = trim(p_config_value),
        value_type = normalized_value_type,
        status = p_status,
        description = nullif(trim(p_description), ''),
        updated_by = actor_id
    where config.id = target_id and config.deleted_at is null;
  end if;
  return app_private.system_config_read_model(target_id);
end;
$$;

create function public.soft_delete_system_configuration(p_id text)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  target_id bigint;
  actor_id bigint;
begin
  perform app_private.require_configuration_permission('configuration.system.update');
  if coalesce(p_id, '') !~ '^[1-9][0-9]*$' then
    raise exception using errcode = '22023', message = 'Configuration ID is invalid';
  end if;
  if p_id::numeric > 9223372036854775807 then
    raise exception using errcode = '22023', message = 'Configuration ID is invalid';
  end if;
  target_id := p_id::bigint;
  select profile.id into actor_id
  from public.profiles as profile
  where profile.auth_user_id = (select auth.uid())
    and profile.is_active
    and profile.deleted_at is null;
  update public.system_configs as config
  set deleted_at = now(), updated_by = actor_id
  where config.id = target_id and config.deleted_at is null;
  if not found then
    raise exception using errcode = 'P0002', message = 'Configuration was not found';
  end if;
end;
$$;

revoke all on function public.admin_dictionary_types(text, text, smallint, integer, integer),
  public.admin_dictionary_items(text),
  public.dictionary_options(text, boolean),
  public.save_dictionary_type(text, text, text, smallint, text),
  public.save_dictionary_item(text, text, text, text, integer, smallint, text),
  public.replace_dictionary_item_order(text, jsonb),
  public.soft_delete_dictionary_type(text),
  public.soft_delete_dictionary_item(text),
  public.admin_system_configurations(text, text, smallint, integer, integer),
  public.system_configuration_value(text),
  public.save_system_configuration(text, text, text, text, text, smallint, text),
  public.soft_delete_system_configuration(text)
  from public, anon, service_role;

grant execute on function public.admin_dictionary_types(text, text, smallint, integer, integer),
  public.admin_dictionary_items(text),
  public.dictionary_options(text, boolean),
  public.save_dictionary_type(text, text, text, smallint, text),
  public.save_dictionary_item(text, text, text, text, integer, smallint, text),
  public.replace_dictionary_item_order(text, jsonb),
  public.soft_delete_dictionary_type(text),
  public.soft_delete_dictionary_item(text),
  public.admin_system_configurations(text, text, smallint, integer, integer),
  public.system_configuration_value(text),
  public.save_system_configuration(text, text, text, text, text, smallint, text),
  public.soft_delete_system_configuration(text)
  to authenticated;
