-- User inbox: message metadata and content remain scoped to each recipient.
create table public.messages (
  id bigint generated by default as identity primary key,
  receiver_id bigint not null references public.profiles (id) on delete cascade,
  sender_id bigint references public.profiles (id) on delete set null,
  title text not null check (length(trim(title)) between 1 and 128),
  summary text check (summary is null or length(summary) <= 255),
  content text not null,
  message_type text not null default 'NOTICE'
    check (length(trim(message_type)) between 1 and 32),
  read_status boolean not null default false,
  sent_at timestamptz not null default now(),
  read_at timestamptz,
  created_by bigint references public.profiles (id) on delete set null,
  created_at timestamptz not null default now(),
  updated_by bigint references public.profiles (id) on delete set null,
  updated_at timestamptz not null default now(),
  deleted boolean not null default false
);

comment on table public.messages is
  'User inbox. Recipients may read their own messages and update only their read state.';

create index messages_receiver_unread_sent_idx
  on public.messages (receiver_id, sent_at desc, id desc)
  where read_status = false and deleted = false;
create index messages_receiver_sent_idx
  on public.messages (receiver_id, sent_at desc, id desc)
  where deleted = false;

create trigger messages_touch_updated_at
before update on public.messages
for each row execute function app_private.touch_updated_at();

alter table public.messages enable row level security;

create policy messages_read_recipient
on public.messages for select to authenticated
using (
  not deleted
  and (select app_private.is_current_profile(receiver_id))
);

create policy messages_update_read_recipient
on public.messages for update to authenticated
using (
  not deleted
  and (select app_private.is_current_profile(receiver_id))
)
with check (
  not deleted
  and (select app_private.is_current_profile(receiver_id))
);

revoke all on public.messages from anon, authenticated;
grant select on public.messages to authenticated;
grant update (read_status, read_at) on public.messages to authenticated;
grant select, insert, update, delete on public.messages to service_role;
grant usage, select on sequence public.messages_id_seq to service_role;

-- PostgREST returns BIGINT as JSON numbers. This invoker view exposes IDs as
-- decimal text so JavaScript never rounds message or profile identifiers.
create view public.message_read_model
with (security_invoker = true)
as
select
  id::text as id,
  receiver_id::text as receiver_id,
  sender_id::text as sender_id,
  title,
  summary,
  content,
  message_type,
  read_status,
  sent_at,
  read_at
from public.messages
where not deleted;

revoke all on public.message_read_model from anon, authenticated, service_role;
grant select on public.message_read_model to authenticated, service_role;

-- One-time legacy import RPC. It is service-role only, idempotent, keeps the
-- source BIGINT IDs, and advances the identity sequence after explicit IDs.
create function public.import_legacy_messages(p_rows jsonb, p_apply boolean)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  source_count integer;
  distinct_id_count integer;
  existing_count integer;
  inserted_count integer := 0;
  maximum_message_id bigint;
begin
  if jsonb_typeof(p_rows) is distinct from 'array' then
    raise exception 'Message import input must be a JSON array';
  end if;

  source_count := jsonb_array_length(p_rows);
  if source_count > 250 then
    raise exception 'Message import batches cannot exceed 250 rows';
  end if;

  if exists (
    select 1 from jsonb_array_elements(p_rows) as source(row)
    where jsonb_typeof(source.row) <> 'object'
       or coalesce(source.row->>'id', '') !~ '^[1-9][0-9]*$'
       or coalesce(source.row->>'receiver_id', '') !~ '^[1-9][0-9]*$'
       or jsonb_typeof(source.row->'title') is distinct from 'string'
       or jsonb_typeof(source.row->'content') is distinct from 'string'
       or coalesce(source.row->>'message_type', '') = ''
       or jsonb_typeof(source.row->'read_status') is distinct from 'boolean'
       or coalesce(source.row->>'sent_at', '') = ''
       or coalesce(source.row->>'created_at', '') = ''
       or coalesce(source.row->>'updated_at', '') = ''
       or jsonb_typeof(source.row->'deleted') is distinct from 'boolean'
  ) then
    raise exception 'Message import contains a row with invalid required fields';
  end if;

  if exists (
    select 1 from jsonb_array_elements(p_rows) as source(row)
    where length(trim(source.row->>'title')) not between 1 and 128
       or length(trim(source.row->>'message_type')) not between 1 and 32
       or (source.row->>'summary') is not null and length(source.row->>'summary') > 255
  ) then
    raise exception 'Message import contains a row outside message field limits';
  end if;

  if exists (
    select 1 from jsonb_array_elements(p_rows) as source(row)
    where (source.row->>'id')::numeric > 9223372036854775807
       or (source.row->>'receiver_id')::numeric > 9223372036854775807
       or (source.row ? 'sender_id' and source.row->>'sender_id' is not null
           and ((source.row->>'sender_id') !~ '^[1-9][0-9]*$'
             or (source.row->>'sender_id')::numeric > 9223372036854775807))
       or (source.row ? 'created_by' and source.row->>'created_by' is not null
           and ((source.row->>'created_by') !~ '^[1-9][0-9]*$'
             or (source.row->>'created_by')::numeric > 9223372036854775807))
       or (source.row ? 'updated_by' and source.row->>'updated_by' is not null
           and ((source.row->>'updated_by') !~ '^[1-9][0-9]*$'
             or (source.row->>'updated_by')::numeric > 9223372036854775807))
  ) then
    raise exception 'Message import contains an ID outside PostgreSQL BIGINT range';
  end if;

  select count(distinct source.row->>'id')::integer
  into distinct_id_count
  from jsonb_array_elements(p_rows) as source(row);
  if distinct_id_count <> source_count then
    raise exception 'Message import batch contains duplicate IDs';
  end if;

  if exists (
    select 1
    from jsonb_to_recordset(p_rows) as source(
      id text,
      receiver_id text,
      sender_id text,
      created_by text,
      updated_by text
    )
    where not exists (
      select 1 from public.profiles as profile
      where profile.id = source.receiver_id::bigint
        and profile.auth_user_id is not null
    )
       or (source.sender_id is not null and not exists (
         select 1 from public.profiles as profile where profile.id = source.sender_id::bigint
       ))
       or (source.created_by is not null and not exists (
         select 1 from public.profiles as profile where profile.id = source.created_by::bigint
       ))
       or (source.updated_by is not null and not exists (
         select 1 from public.profiles as profile where profile.id = source.updated_by::bigint
       ))
  ) then
    raise exception 'Message import references an unmapped business profile';
  end if;

  if exists (
    with source_rows as (
      select * from jsonb_to_recordset(p_rows) as source(
        id text,
        receiver_id text,
        sender_id text,
        title text,
        summary text,
        content text,
        message_type text,
        read_status boolean,
        sent_at timestamptz,
        read_at timestamptz,
        created_by text,
        created_at timestamptz,
        updated_by text,
        updated_at timestamptz,
        deleted boolean
      )
    )
    select 1
    from source_rows as source
    join public.messages as existing on existing.id = source.id::bigint
    where existing.receiver_id <> source.receiver_id::bigint
       or existing.sender_id is distinct from source.sender_id::bigint
       or existing.title is distinct from source.title
       or existing.summary is distinct from source.summary
       or existing.content is distinct from source.content
       or existing.message_type is distinct from source.message_type
       or existing.read_status is distinct from source.read_status
       or existing.sent_at is distinct from source.sent_at
       or existing.read_at is distinct from source.read_at
       or existing.created_by is distinct from source.created_by::bigint
       or existing.created_at is distinct from source.created_at
       or existing.updated_by is distinct from source.updated_by::bigint
       or existing.updated_at is distinct from source.updated_at
       or existing.deleted is distinct from source.deleted
  ) then
    raise exception 'Message import conflicts with an existing message ID';
  end if;

  select count(*)::integer
  into existing_count
  from jsonb_to_recordset(p_rows) as source(id text)
  join public.messages as existing on existing.id = source.id::bigint;

  if p_apply and source_count > existing_count then
    insert into public.messages (
      id, receiver_id, sender_id, title, summary, content, message_type,
      read_status, sent_at, read_at, created_by, created_at,
      updated_by, updated_at, deleted
    )
    select
      source.id::bigint,
      source.receiver_id::bigint,
      source.sender_id::bigint,
      source.title,
      source.summary,
      source.content,
      source.message_type,
      source.read_status,
      source.sent_at,
      source.read_at,
      source.created_by::bigint,
      source.created_at,
      source.updated_by::bigint,
      source.updated_at,
      source.deleted
    from jsonb_to_recordset(p_rows) as source(
      id text,
      receiver_id text,
      sender_id text,
      title text,
      summary text,
      content text,
      message_type text,
      read_status boolean,
      sent_at timestamptz,
      read_at timestamptz,
      created_by text,
      created_at timestamptz,
      updated_by text,
      updated_at timestamptz,
      deleted boolean
    )
    on conflict (id) do nothing;

    get diagnostics inserted_count = row_count;
    select max(id) into maximum_message_id from public.messages;
    if maximum_message_id is not null then
      perform pg_catalog.setval(
        pg_catalog.pg_get_serial_sequence('public.messages', 'id'),
        maximum_message_id,
        true
      );
    end if;
  end if;

  return jsonb_build_object(
    'sourceCount', source_count,
    'alreadyPresentCount', existing_count,
    'rowsToInsert', source_count - existing_count,
    'insertedCount', inserted_count,
    'applied', p_apply
  );
end;
$$;

revoke all on function public.import_legacy_messages(jsonb, boolean)
  from public, anon, authenticated;
grant execute on function public.import_legacy_messages(jsonb, boolean) to service_role;
comment on function public.import_legacy_messages(jsonb, boolean) is
  'Local source-message backfill RPC. Service-role only, idempotent, and preserves signed BIGINT IDs.';

alter publication supabase_realtime add table public.messages;
