insert into public.permission_catalog (permission_key, description)
values
  ('files.attachments.read', '读取授权范围内的附件'),
  ('files.attachments.upload', '上传附件'),
  ('files.attachments.delete', '删除授权范围内的附件')
on conflict (permission_key) do update
set description = excluded.description;

create table public.attachments (
  id bigint generated by default as identity primary key,
  original_name text not null check (
    length(trim(original_name)) between 1 and 255
    and original_name !~ '[[:cntrl:]]'
  ),
  storage_path text not null unique check (length(storage_path) <= 512),
  mime_type text not null check (length(mime_type) between 1 and 128),
  file_ext text not null check (length(file_ext) between 1 and 32),
  file_size bigint not null check (file_size between 0 and 20971520),
  business_module text,
  business_record_id bigint,
  reference_status smallint not null default 0 check (reference_status in (0, 1)),
  upload_user_id bigint not null references public.profiles (id) on delete restrict,
  uploaded_at timestamptz not null default now(),
  created_by bigint references public.profiles (id) on delete set null,
  updated_by bigint references public.profiles (id) on delete set null,
  deleted_at timestamptz,
  constraint attachments_business_reference_pair check (
    (business_module is null and business_record_id is null)
    or (nullif(trim(business_module), '') is not null and business_record_id > 0)
  ),
  constraint attachments_reference_status_matches_link check (
    reference_status = case when business_module is null then 0 else 1 end
  )
);

create index attachments_active_uploaded_idx
  on public.attachments (uploaded_at desc, id desc)
  where deleted_at is null;
create index attachments_business_active_idx
  on public.attachments (business_module, business_record_id, uploaded_at desc)
  where deleted_at is null;
create index attachments_uploader_uploaded_idx
  on public.attachments (upload_user_id, uploaded_at desc)
  where deleted_at is null;

comment on table public.attachments is
  'Private Storage metadata. All file access is checked by Storage RLS and module permissions.';
comment on column public.attachments.storage_path is
  'Opaque object key inside the private admin-attachments bucket; never a public URL.';

alter table public.attachments enable row level security;
revoke all on public.attachments from public, anon, authenticated;
grant select on public.attachments to authenticated;
grant all on public.attachments to service_role;
grant usage, select on sequence public.attachments_id_seq to service_role;

create policy attachments_read_authorized
on public.attachments for select to authenticated
using (
  deleted_at is null
  and (select app_private.is_password_authenticated())
  and (select app_private.has_permission('files.attachments.read'))
);

create view public.attachment_read_model
with (security_invoker = true)
as
select
  id::text as id,
  original_name,
  storage_path,
  mime_type,
  file_ext,
  file_size,
  business_module,
  business_record_id::text as business_record_id,
  reference_status,
  upload_user_id::text as upload_user_id,
  uploaded_at
from public.attachments
where deleted_at is null;

revoke all on public.attachment_read_model from public, anon;
grant select on public.attachment_read_model to authenticated;

insert into storage.buckets (id, name, public, file_size_limit)
values ('admin-attachments', 'admin-attachments', false, 20971520)
on conflict (id) do update
set name = excluded.name,
    public = false,
    file_size_limit = excluded.file_size_limit;

create policy admin_attachments_upload_authorized
on storage.objects for insert to authenticated
with check (
  bucket_id = 'admin-attachments'
  and (select app_private.is_password_authenticated())
  and (select app_private.has_permission('files.attachments.upload'))
  and owner_id = (select auth.uid()::text)
  and cardinality(storage.foldername(name)) = 1
  and (storage.foldername(name))[1] = (select public.current_business_user_id())
);

create policy admin_attachments_read_authorized
on storage.objects for select to authenticated
using (
  bucket_id = 'admin-attachments'
  and (select app_private.is_password_authenticated())
  and (select app_private.has_permission('files.attachments.read'))
  and exists (
    select 1
    from public.attachments as attachment
    where attachment.storage_path = storage.objects.name
      and attachment.deleted_at is null
  )
);

create function app_private.can_delete_attachment_path(p_storage_path text)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select (select auth.uid()) is not null
    and (select app_private.is_password_authenticated())
    and (select app_private.has_permission('files.attachments.delete'))
    and exists (
      select 1
      from public.attachments as attachment
      where attachment.storage_path = p_storage_path
    );
$$;

revoke all on function app_private.can_delete_attachment_path(text) from public, anon;
grant execute on function app_private.can_delete_attachment_path(text) to authenticated;

create function app_private.can_cleanup_unregistered_attachment_upload(p_storage_path text)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select (select auth.uid()) is not null
    and (select app_private.is_password_authenticated())
    and (select app_private.has_permission('files.attachments.upload'))
    and exists (
      select 1
      from storage.objects as object
      where object.bucket_id = 'admin-attachments'
        and object.name = p_storage_path
        and object.owner_id = (select auth.uid()::text)
        and cardinality(storage.foldername(object.name)) = 1
        and (storage.foldername(object.name))[1] = (select public.current_business_user_id())
    )
    and not exists (
      select 1
      from public.attachments as attachment
      where attachment.storage_path = p_storage_path
    );
$$;

revoke all on function app_private.can_cleanup_unregistered_attachment_upload(text)
  from public, anon;
grant execute on function app_private.can_cleanup_unregistered_attachment_upload(text)
  to authenticated;

create policy admin_attachments_delete_authorized
on storage.objects for delete to authenticated
using (
  bucket_id = 'admin-attachments'
  and (
    (select app_private.can_delete_attachment_path(storage.objects.name))
    or (select app_private.can_cleanup_unregistered_attachment_upload(storage.objects.name))
  )
);

create function public.create_attachment_metadata(
  p_original_name text,
  p_storage_path text,
  p_mime_type text,
  p_file_ext text,
  p_file_size bigint,
  p_business_module text,
  p_business_record_id bigint
)
returns public.attachments
language plpgsql
security definer
set search_path = ''
as $$
declare
  actor_id bigint;
  created_attachment public.attachments;
begin
  if (select auth.uid()) is null
     or not (select app_private.is_password_authenticated()) then
    raise exception using errcode = '42501', message = 'A registered password session is required';
  end if;
  if not (select app_private.has_permission('files.attachments.upload')) then
    raise exception using errcode = '42501', message = 'Attachment upload permission is required';
  end if;

  actor_id := (select public.current_business_user_id())::bigint;
  if actor_id is null
     or nullif(trim(p_original_name), '') is null
     or length(p_original_name) > 255
     or p_original_name ~ '[[:cntrl:]]'
     or p_storage_path is null
     or p_mime_type is null
     or nullif(trim(p_mime_type), '') is null
     or length(p_mime_type) > 128
     or p_file_ext is null
     or p_file_ext !~ '^[a-z0-9]{1,32}$'
     or p_file_size is null
     or p_file_size not between 0 and 20971520
     or ((p_business_module is null) <> (p_business_record_id is null))
     or (p_business_module is not null and (
       nullif(trim(p_business_module), '') is null
       or length(p_business_module) > 64
       or p_business_record_id <= 0
     ))
     or p_storage_path !~ ('^' || actor_id::text || '/[0-9a-f-]{36}\.[a-z0-9]{1,32}$') then
    raise exception using errcode = '22023', message = 'Attachment metadata is invalid';
  end if;

  if not exists (
    select 1
    from storage.objects as object
    where object.bucket_id = 'admin-attachments'
      and object.name = p_storage_path
      and object.owner_id = (select auth.uid()::text)
  ) then
    raise exception using errcode = '23503', message = 'Uploaded storage object is missing';
  end if;

  insert into public.attachments (
    original_name,
    storage_path,
    mime_type,
    file_ext,
    file_size,
    business_module,
    business_record_id,
    reference_status,
    upload_user_id,
    created_by,
    updated_by
  ) values (
    trim(p_original_name),
    p_storage_path,
    trim(p_mime_type),
    p_file_ext,
    p_file_size,
    nullif(trim(p_business_module), ''),
    p_business_record_id,
    case when nullif(trim(p_business_module), '') is null then 0 else 1 end,
    actor_id,
    actor_id,
    actor_id
  ) returning * into created_attachment;

  return created_attachment;
end;
$$;

revoke all on function public.create_attachment_metadata(text, text, text, text, bigint, text, bigint)
  from public, anon;
grant execute on function public.create_attachment_metadata(text, text, text, text, bigint, text, bigint)
  to authenticated;
comment on function public.create_attachment_metadata(text, text, text, text, bigint, text, bigint) is
  'Creates metadata for a private Storage object after checking the caller session, permission, path and object.';

create function public.attachment_storage_path_for_delete(p_attachment_id bigint)
returns text
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  object_path text;
begin
  if (select auth.uid()) is null
     or not (select app_private.is_password_authenticated())
     or not (select app_private.has_permission('files.attachments.delete')) then
    raise exception using errcode = '42501', message = 'Attachment delete permission is required';
  end if;

  select attachment.storage_path into object_path
  from public.attachments as attachment
  where attachment.id = p_attachment_id
    and attachment.deleted_at is null;

  if object_path is null then
    raise exception using errcode = 'P0002', message = 'Attachment does not exist';
  end if;
  return object_path;
end;
$$;

revoke all on function public.attachment_storage_path_for_delete(bigint) from public, anon;
grant execute on function public.attachment_storage_path_for_delete(bigint) to authenticated;

create function public.delete_attachment_metadata(p_attachment_id bigint)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  actor_id bigint;
begin
  if (select auth.uid()) is null
     or not (select app_private.is_password_authenticated())
     or not (select app_private.has_permission('files.attachments.delete')) then
    raise exception using errcode = '42501', message = 'Attachment delete permission is required';
  end if;

  actor_id := (select public.current_business_user_id())::bigint;
  update public.attachments as attachment
  set deleted_at = now(),
      reference_status = 0,
      updated_by = actor_id
  where attachment.id = p_attachment_id
    and attachment.deleted_at is null;

  if not found then
    raise exception using errcode = 'P0002', message = 'Attachment does not exist';
  end if;
  return true;
end;
$$;

revoke all on function public.delete_attachment_metadata(bigint) from public, anon;
grant execute on function public.delete_attachment_metadata(bigint) to authenticated;

comment on function public.attachment_storage_path_for_delete(bigint) is
  'Returns the private object path only after checking the caller session and delete permission.';
comment on function public.delete_attachment_metadata(bigint) is
  'Soft-deletes attachment metadata after the authenticated client removes the private object.';
